apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-worker
  namespace: devtrack
  labels:
    app: playwright-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playwright-worker
  template:
    metadata:
      labels:
        app: playwright-worker
    spec:
      containers:
      - name: playwright-worker
        image: swp391-su26-ai-audit-project-swp391_se20a11_group-04-1-playwright-worker:latest
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: devtrack-secrets
        env:
        # Ghi đè các biến networking vì K8s pod cần gọi ra ngoài máy Windows (host)
        - name: KAFKA_BROKERS
          value: "host.docker.internal:9094"
        - name: WS_URL
          value: "ws://host.docker.internal:4001"
        - name: BACKEND_URL
          value: "http://host.docker.internal:8080"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
