/**
 * Sinh Playwright script từ steps_structured
 * Không cần AI, không tốn token
 */
function generateFromTemplate(testCase, runId) {
    const { title, base_url, steps_structured } = testCase;

    const stepCode = steps_structured
        .sort((a, b) => a.order - b.order)
        .map((step, index) => {
            const stepNum = index + 1;
            let code = '';

            const sel = (step.selector || '').replace(/"/g, '\\"');
            const val = (step.value || '').replace(/"/g, '\\"');
            const exp = (step.expected || '').replace(/"/g, '\\"');
            const pth = (step.path || '').replace(/"/g, '\\"');

            switch (step.action) {
                case 'goto':
                    code = `await page.goto("${base_url}${pth}");\n    await page.waitForTimeout(800);`;
                    break;
                case 'fill':
                    if (/^\d{4}-\d{2}-\d{2}$/.test(val)) {
                        code = `await highlight("${sel}", "Chọn ngày: ${val}");\n    await page.fill("${sel}", "${val}");\n    await page.waitForTimeout(200);`;
                    } else {
                        code = `await highlight("${sel}", "Gõ: ${val}");\n    await page.fill("${sel}", "");\n    await page.locator("${sel}").pressSequentially("${val}", { delay: 50 });\n    await page.waitForTimeout(200);`;
                    }
                    break;
                case 'click':
                    code = `await highlight("${sel}", "Click");\n    await page.click("${sel}");\n    await page.waitForTimeout(500);`;
                    break;
                case 'wait_for':
                    code = `await page.waitForSelector("${sel}", { timeout: 5000 });`;
                    break;
                case 'select':
                    code = `await highlight("${sel}", "Chọn: ${val}");\n    await page.selectOption("${sel}", "${val}");\n    await page.waitForTimeout(500);`;
                    break;
                case 'expect_url':
                    code = `await expect(page).toHaveURL("${base_url}${exp}");`;
                    break;
                case 'expect_text':
                    code = `await highlight("${sel}", "Check Text: ${exp}");\n    await expect(page.locator("${sel}")).toContainText("${exp}");`;
                    break;
                case 'expect_visible':
                    code = `await highlight("${sel}", "Check Visible");\n    await expect(page.locator("${sel}")).toBeVisible();`;
                    break;
                case 'expect_hidden':
                    code = `await expect(page.locator("${sel}")).toBeHidden();`;
                    break;
                default:
                    code = `// [UNKNOWN ACTION] ${step.action}`;
            }

            const autoScreenshot = ['click', 'fill', 'select', 'expect_url', 'expect_text', 'expect_visible', 'expect_hidden'].includes(step.action)
                ? `\n    await page.screenshot({ path: 'step-${stepNum}-after.png' });`
                : '';

            const stepDesc = (step.description || step.action).replace(/"/g, '\\"');
            return `  // Step ${stepNum}
  await test.step("${stepDesc}", async () => {
    ${code}${autoScreenshot}
  });`;
        })
        .join('\n\n');

    return `
const { test, expect } = require('@playwright/test');
const WebSocket = require('ws');

test("${title}", async ({ page }) => {
  // Auto-generated by DevTrack Template Engine
  // Generated at: ${new Date().toISOString()}

  // Setup CDP Screencast WebSocket Stream
  const ws = new WebSocket("ws://localhost:4000/?runId=${runId}&role=provider");
  
  // Wait for WebSocket to be fully connected before starting CDP screencast
  // This prevents early frames from being silently dropped
  await new Promise((resolve, reject) => {
    if (ws.readyState === WebSocket.OPEN) return resolve();
    ws.on('open', resolve);
    ws.on('error', reject);
    setTimeout(resolve, 3000); // Safety timeout
  });

  const client = await page.context().newCDPSession(page);
  await client.send('Page.startScreencast', { format: 'jpeg', quality: 50, everyNthFrame: 1 });
  client.on('Page.screencastFrame', async (frameObject) => {
      if (ws.readyState === WebSocket.OPEN) {
          ws.send(JSON.stringify({ type: 'frame', data: frameObject.data }));
      }
      try { await client.send('Page.screencastFrameAck', { sessionId: frameObject.sessionId }); } catch(e){}
  });

  // Brief pause so the frontend client WS can connect and server can buffer first frame
  await page.waitForTimeout(300);

  // Inject a highlighter function
  async function highlight(selector, text) {
    try {
      await page.evaluate(({sel, txt}) => {
        const el = document.querySelector(sel);
        if (el) {
          document.querySelectorAll('.playwright-highlight').forEach(e => e.remove());
          const rect = el.getBoundingClientRect();
          const box = document.createElement('div');
          box.className = 'playwright-highlight';
          box.style.position = 'absolute';
          box.style.border = '3px solid red';
          box.style.boxShadow = '0 0 15px red';
          box.style.top = (rect.top + window.scrollY - 4) + 'px';
          box.style.left = (rect.left + window.scrollX - 4) + 'px';
          box.style.width = (rect.width + 8) + 'px';
          box.style.height = (rect.height + 8) + 'px';
          box.style.zIndex = '999999';
          box.style.pointerEvents = 'none';
          
          const tooltip = document.createElement('div');
          tooltip.style.position = 'absolute';
          tooltip.style.background = 'red';
          tooltip.style.color = 'white';
          tooltip.style.padding = '4px 8px';
          tooltip.style.fontSize = '12px';
          tooltip.style.top = '-25px';
          tooltip.style.left = '0';
          tooltip.style.borderRadius = '4px';
          tooltip.style.fontWeight = 'bold';
          tooltip.innerText = txt;
          box.appendChild(tooltip);
          
          document.body.appendChild(box);
        }
      }, { sel: selector, txt: text });
      await page.waitForTimeout(400);
    } catch(e) {}
  }

${stepCode}

  // Close WS at the end
  try { ws.close(); } catch(e){}
});
  `.trim();
}

module.exports = { generateFromTemplate };