const { test, expect } = require('@playwright/test');
const WebSocket = require('ws');

test("Tạo dự án mới thành công", async ({ page }) => {
  // Auto-generated by DevTrack Template Engine
  // Generated at: 2026-06-09T04:25:56.836Z

  // Setup CDP Screencast WebSocket Stream
  const wsUrl = process.env.WS_URL || "ws://localhost:4001";
  const ws = new WebSocket(`${wsUrl}/?runId=101&role=provider`);
  
  // Wait for WebSocket to be fully connected before starting CDP screencast
  // This prevents early frames from being silently dropped
  await new Promise((resolve, reject) => {
    if (ws.readyState === WebSocket.OPEN) return resolve();
    ws.on('open', resolve);
    ws.on('error', reject);
    setTimeout(resolve, 3000); // Safety timeout
  });

  const client = await page.context().newCDPSession(page);
  await client.send('Page.startScreencast', { format: 'jpeg', quality: 50, everyNthFrame: 1 });
  client.on('Page.screencastFrame', async (frameObject) => {
      if (ws.readyState === WebSocket.OPEN) {
          ws.send(JSON.stringify({ type: 'frame', data: frameObject.data }));
      }
      try { await client.send('Page.screencastFrameAck', { sessionId: frameObject.sessionId }); } catch(e){}
  });

  // Brief pause so the frontend client WS can connect and server can buffer first frame
  await page.waitForTimeout(300);

  // Inject a highlighter function
  async function highlight(selector, text) {
    try {
      await page.evaluate(({sel, txt}) => {
        const el = document.querySelector(sel);
        if (el) {
          document.querySelectorAll('.playwright-highlight').forEach(e => e.remove());
          const rect = el.getBoundingClientRect();
          const box = document.createElement('div');
          box.className = 'playwright-highlight';
          box.style.position = 'absolute';
          box.style.border = '3px solid red';
          box.style.boxShadow = '0 0 15px red';
          box.style.top = (rect.top + window.scrollY - 4) + 'px';
          box.style.left = (rect.left + window.scrollX - 4) + 'px';
          box.style.width = (rect.width + 8) + 'px';
          box.style.height = (rect.height + 8) + 'px';
          box.style.zIndex = '999999';
          box.style.pointerEvents = 'none';
          
          const tooltip = document.createElement('div');
          tooltip.style.position = 'absolute';
          tooltip.style.background = 'red';
          tooltip.style.color = 'white';
          tooltip.style.padding = '4px 8px';
          tooltip.style.fontSize = '12px';
          tooltip.style.top = '-25px';
          tooltip.style.left = '0';
          tooltip.style.borderRadius = '4px';
          tooltip.style.fontWeight = 'bold';
          tooltip.innerText = txt;
          box.appendChild(tooltip);
          
          document.body.appendChild(box);
        }
      }, { sel: selector, txt: text });
      await page.waitForTimeout(400);
    } catch(e) {}
  }

  // Step 1
  await test.step("Mở trang đăng nhập", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 0 })); } catch(e){}
    }
    await page.goto("http://localhost:5173/login", { timeout: 15000 });
    await page.waitForTimeout(800);
  });

  // Step 2
  await test.step("Nhập email đăng nhập", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 1 })); } catch(e){}
    }
    await highlight("#usernameOrEmail", "Gõ: kikiki");
    await page.fill("#usernameOrEmail", "", { timeout: 5000 });
    await page.locator("#usernameOrEmail").pressSequentially("kikiki", { delay: 50, timeout: 5000 });
    await page.waitForTimeout(200);
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-2-after.png' });
  });

  // Step 3
  await test.step("Nhập mật khẩu", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 2 })); } catch(e){}
    }
    await highlight("#password", "Gõ: 111111");
    await page.fill("#password", "", { timeout: 5000 });
    await page.locator("#password").pressSequentially("111111", { delay: 50, timeout: 5000 });
    await page.waitForTimeout(200);
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-3-after.png' });
  });

  // Step 4
  await test.step("Click nút đăng nhập", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 3 })); } catch(e){}
    }
    await highlight("button[type='submit']", "Click");
    await page.click("button[type='submit']", { timeout: 5000 });
    await page.waitForTimeout(500);
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-4-after.png' });
  });

  // Step 5
  await test.step("Kiểm tra redirect về Dashboard", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 4 })); } catch(e){}
    }
    await expect(page, "Lỗi URL: Trang hiện tại không khớp. Bạn có quên bước Đăng nhập không?").toHaveURL("http://localhost:5173/dashboard", { timeout: 5000 });
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-5-after.png' });
  });

  // Step 6
  await test.step("Click nút Create Project", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 5 })); } catch(e){}
    }
    await highlight("button:has-text('Create Project')", "Click");
    await page.click("button:has-text('Create Project')", { timeout: 5000 });
    await page.waitForTimeout(500);
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-6-after.png' });
  });

  // Step 7
  await test.step("Nhập tên dự án", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 6 })); } catch(e){}
    }
    await highlight("#projName", "Gõ: huncu");
    await page.fill("#projName", "", { timeout: 5000 });
    await page.locator("#projName").pressSequentially("huncu", { delay: 50, timeout: 5000 });
    await page.waitForTimeout(200);
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-7-after.png' });
  });

  // Step 8
  await test.step("Nhập chuyên ngành", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 7 })); } catch(e){}
    }
    await highlight("#projMajor", "Gõ: Software Engineering");
    await page.fill("#projMajor", "", { timeout: 5000 });
    await page.locator("#projMajor").pressSequentially("Software Engineering", { delay: 50, timeout: 5000 });
    await page.waitForTimeout(200);
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-8-after.png' });
  });

  // Step 9
  await test.step("Nhập hạn chót", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 8 })); } catch(e){}
    }
    await highlight("#projDeadline", "Chọn ngày: 2026-08-30");
    await page.fill("#projDeadline", "2026-08-30", { timeout: 5000 });
    await page.waitForTimeout(200);
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-9-after.png' });
  });

  // Step 10
  await test.step("Nhập mô tả dự án", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 9 })); } catch(e){}
    }
    await highlight("#projDesc", "Gõ: Đây là dự án test tự động bởi DevTrack AI");
    await page.fill("#projDesc", "", { timeout: 5000 });
    await page.locator("#projDesc").pressSequentially("Đây là dự án test tự động bởi DevTrack AI", { delay: 50, timeout: 5000 });
    await page.waitForTimeout(200);
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-10-after.png' });
  });

  // Step 11
  await test.step("Click nút Create Project trong modal", async () => {
    if (ws.readyState === WebSocket.OPEN) {
      try { ws.send(JSON.stringify({ type: 'step_started', stepIndex: 10 })); } catch(e){}
    }
    await highlight("button[type='submit']:has-text('Create Project')", "Click");
    await page.click("button[type='submit']:has-text('Create Project')", { timeout: 5000 });
    await page.waitForTimeout(500);
    await page.screenshot({ path: 'D:/FPTU/semeter_5/DevTrackAI/swp391-su26-ai-audit-project-swp391_se20a11_group-04-1/code/playwright-service/temp/101/screenshots/step-11-after.png' });
  });

  // Close WS at the end
  try { ws.close(); } catch(e){}
});