-- Migration: V20260522002000__create_project_invitations_table.sql
-- Date: 2026-05-22
-- Author: Antigravity
-- Description: Create project_invitations table for websocket direct invitations

CREATE TABLE project_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    inviter_id BIGINT NOT NULL,
    invitee_id BIGINT NOT NULL,
    token VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP NOT NULL,
    
    CONSTRAINT fk_project_invitations_project 
        FOREIGN KEY (project_id) 
        REFERENCES projects(id) 
        ON DELETE CASCADE,
        
    CONSTRAINT fk_project_invitations_inviter 
        FOREIGN KEY (inviter_id) 
        REFERENCES user_accounts(id) 
        ON DELETE CASCADE,
        
    CONSTRAINT fk_project_invitations_invitee 
        FOREIGN KEY (invitee_id) 
        REFERENCES user_accounts(id) 
        ON DELETE CASCADE
);
