-- Migration: V20260527213000__add_task_sla_digest_support.sql
-- Date: 2026-05-27
-- Author: Codex
-- Description: Add task SLA, digest, outbox, and scheduler log support

ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS weight NUMERIC(3,1) NOT NULL DEFAULT 1.0,
    ADD COLUMN IF NOT EXISTS overdue_penalty_applied BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS overdue_penalty_applied_at TIMESTAMP;

ALTER TABLE tasks
    ADD CONSTRAINT chk_tasks_weight_range
        CHECK (weight >= 1.0 AND weight <= 2.0);

CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbox_events_status_created
    ON outbox_events(status, created_at);

CREATE TABLE IF NOT EXISTS task_penalty_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reason VARCHAR(100) NOT NULL,
    penalty_label VARCHAR(100) NOT NULL DEFAULT 'OVERDUE_PENALTY',
    applied_by VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    immutable BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_task_penalty_logs_task
        FOREIGN KEY (task_id)
            REFERENCES tasks(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_task_penalty_logs_user
        FOREIGN KEY (user_id)
            REFERENCES user_accounts(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_task_penalty_logs_task_reason
    ON task_penalty_logs(task_id, reason);

CREATE TABLE IF NOT EXISTS daily_digests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    digest_date DATE NOT NULL,
    digest_type VARCHAR(50) NOT NULL DEFAULT 'DAILY_MEMBER_DIGEST',
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    item_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    last_error TEXT,

    CONSTRAINT fk_daily_digests_user
        FOREIGN KEY (user_id)
            REFERENCES user_accounts(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_daily_digests_user_date_type
    ON daily_digests(user_id, digest_date, digest_type);

CREATE TABLE IF NOT EXISTS daily_digest_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    deadline DATE,
    penalty_label VARCHAR(100),
    note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_daily_digest_items_digest
        FOREIGN KEY (digest_id)
            REFERENCES daily_digests(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_daily_digest_items_task
        FOREIGN KEY (task_id)
            REFERENCES tasks(id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_daily_digest_items_digest
    ON daily_digest_items(digest_id);

CREATE TABLE IF NOT EXISTS email_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT,
    recipient_email VARCHAR(255) NOT NULL,
    email_type VARCHAR(50) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    related_id BIGINT,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,

    CONSTRAINT fk_email_logs_recipient
        FOREIGN KEY (recipient_id)
            REFERENCES user_accounts(id)
);

CREATE INDEX IF NOT EXISTS idx_email_logs_type_status
    ON email_logs(email_type, status, created_at);

CREATE TABLE IF NOT EXISTS scheduler_run_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP,
    total_scanned INTEGER NOT NULL DEFAULT 0,
    total_created INTEGER NOT NULL DEFAULT 0,
    total_sent INTEGER NOT NULL DEFAULT 0,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_scheduler_run_logs_job_started
    ON scheduler_run_logs(job_name, started_at);
