-- Migration: V20260527233000__add_weekly_report_support.sql
-- Date: 2026-05-27
-- Author: Codex
-- Description: Add weekly project risk report support

CREATE TABLE IF NOT EXISTS weekly_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    report_week_start DATE NOT NULL,
    report_week_end DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'GENERATED',
    red_member_count INTEGER NOT NULL DEFAULT 0,
    total_overdue_tasks INTEGER NOT NULL DEFAULT 0,
    total_penalized_tasks INTEGER NOT NULL DEFAULT 0,
    summary TEXT,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    generated_by VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',

    CONSTRAINT fk_weekly_reports_project
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_weekly_reports_project_week
    ON weekly_reports(project_id, report_week_start, report_week_end);

CREATE TABLE IF NOT EXISTS weekly_report_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weekly_report_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    overdue_task_count INTEGER NOT NULL DEFAULT 0,
    frozen_task_count INTEGER NOT NULL DEFAULT 0,
    penalized_task_count INTEGER NOT NULL DEFAULT 0,
    stale_explanation_count INTEGER NOT NULL DEFAULT 0,
    risk_level VARCHAR(30) NOT NULL DEFAULT 'RED',
    reason TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_weekly_report_members_report
        FOREIGN KEY (weekly_report_id)
            REFERENCES weekly_reports(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_weekly_report_members_user
        FOREIGN KEY (user_id)
            REFERENCES user_accounts(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_weekly_report_members_report_user
    ON weekly_report_members(weekly_report_id, user_id);
