CREATE TABLE IF NOT EXISTS code_insight_evidence_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    evidence_type VARCHAR(30) NOT NULL,
    evidence_id BIGINT NOT NULL,
    source VARCHAR(40) NOT NULL,
    confidence VARCHAR(30) NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_code_insight_evidence_links_project
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_code_insight_evidence_links_task
        FOREIGN KEY (task_id)
            REFERENCES tasks(id)
            ON DELETE CASCADE,

    CONSTRAINT uk_code_insight_evidence_links_target
        UNIQUE (project_id, task_id, evidence_type, evidence_id),

    CONSTRAINT chk_code_insight_evidence_links_type
        CHECK (evidence_type IN ('COMMIT', 'PULL_REQUEST', 'CHECK_RUN')),

    CONSTRAINT chk_code_insight_evidence_links_source
        CHECK (source IN ('BRANCH_NAME', 'PR_TITLE', 'PR_BODY', 'COMMIT_MESSAGE', 'GITHUB_ISSUE_NUMBER', 'SHA_CHAIN')),

    CONSTRAINT chk_code_insight_evidence_links_confidence
        CHECK (confidence IN ('HIGH', 'MEDIUM', 'LOW', 'CONFIRMED'))
);

CREATE INDEX IF NOT EXISTS idx_code_insight_evidence_links_task
    ON code_insight_evidence_links(task_id, evidence_type);

CREATE INDEX IF NOT EXISTS idx_code_insight_evidence_links_project
    ON code_insight_evidence_links(project_id, evidence_type);
