-- =========================================================
-- Task Proposals & Comments (Discussion Module)
-- Each Task can have many Proposals (checklist suggestions).
-- Each Proposal can have many Comments and Vote records.
-- =========================================================

CREATE TYPE proposal_status_enum AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TABLE task_proposals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT NOT NULL,
    content     TEXT NOT NULL,
    status      proposal_status_enum NOT NULL DEFAULT 'PENDING',
    created_by  BIGINT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_proposals_task
        FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,

    CONSTRAINT fk_task_proposals_created_by
        FOREIGN KEY (created_by) REFERENCES user_accounts(id)
);

CREATE TABLE task_proposal_votes (
    proposal_id BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    is_upvote   BOOLEAN NOT NULL DEFAULT TRUE,  -- TRUE = upvote, FALSE = downvote

    PRIMARY KEY (proposal_id, user_id),

    CONSTRAINT fk_task_proposal_votes_proposal
        FOREIGN KEY (proposal_id) REFERENCES task_proposals(id) ON DELETE CASCADE,

    CONSTRAINT fk_task_proposal_votes_user
        FOREIGN KEY (user_id) REFERENCES user_accounts(id) ON DELETE CASCADE
);

CREATE TABLE task_proposal_comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    content     TEXT NOT NULL,
    created_by  BIGINT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_proposal_comments_proposal
        FOREIGN KEY (proposal_id) REFERENCES task_proposals(id) ON DELETE CASCADE,

    CONSTRAINT fk_task_proposal_comments_user
        FOREIGN KEY (created_by) REFERENCES user_accounts(id)
);
