-- Migration: V20260527233000__add_weekly_report_support.sql
-- Date: 2026-05-27
-- Author: Codex
-- Description: Add weekly project risk report support

ALTER TABLE weekly_reports
    DROP CONSTRAINT IF EXISTS fk_weekly_reports_generated_by;

ALTER TABLE weekly_reports
    ADD COLUMN IF NOT EXISTS report_week_start DATE,
    ADD COLUMN IF NOT EXISTS report_week_end DATE,
    ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'GENERATED',
    ADD COLUMN IF NOT EXISTS red_member_count INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_overdue_tasks INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_penalized_tasks INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS summary TEXT,
    ADD COLUMN IF NOT EXISTS generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE weekly_reports
SET
    report_week_start = COALESCE(report_week_start, CURRENT_DATE),
    report_week_end = COALESCE(report_week_end, CURRENT_DATE),
    status = COALESCE(status, 'GENERATED'),
    red_member_count = COALESCE(red_member_count, 0),
    total_overdue_tasks = COALESCE(total_overdue_tasks, 0),
    total_penalized_tasks = COALESCE(total_penalized_tasks, 0),
    generated_at = COALESCE(generated_at, CURRENT_TIMESTAMP);

ALTER TABLE weekly_reports
    ALTER COLUMN report_week_start SET NOT NULL,
    ALTER COLUMN report_week_end SET NOT NULL,
    ALTER COLUMN status SET NOT NULL,
    ALTER COLUMN red_member_count SET NOT NULL,
    ALTER COLUMN total_overdue_tasks SET NOT NULL,
    ALTER COLUMN total_penalized_tasks SET NOT NULL,
    ALTER COLUMN generated_at SET NOT NULL;

ALTER TABLE weekly_reports
    ALTER COLUMN generated_by TYPE VARCHAR(50)
        USING COALESCE('USER_' || generated_by::TEXT, 'SYSTEM'),
    ALTER COLUMN generated_by SET DEFAULT 'SYSTEM';

UPDATE weekly_reports
SET generated_by = 'SYSTEM'
WHERE generated_by IS NULL OR generated_by = '';

ALTER TABLE weekly_reports
    ALTER COLUMN generated_by SET NOT NULL;

ALTER TABLE weekly_reports
    DROP COLUMN IF EXISTS sprint_id,
    DROP COLUMN IF EXISTS week_number,
    DROP COLUMN IF EXISTS content_markdown,
    DROP COLUMN IF EXISTS input_snapshot,
    DROP COLUMN IF EXISTS created_at;

CREATE UNIQUE INDEX IF NOT EXISTS uq_weekly_reports_project_week
    ON weekly_reports(project_id, report_week_start, report_week_end);

CREATE TABLE IF NOT EXISTS weekly_report_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weekly_report_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    overdue_task_count INTEGER NOT NULL DEFAULT 0,
    frozen_task_count INTEGER NOT NULL DEFAULT 0,
    penalized_task_count INTEGER NOT NULL DEFAULT 0,
    stale_explanation_count INTEGER NOT NULL DEFAULT 0,
    risk_level VARCHAR(30) NOT NULL DEFAULT 'RED',
    reason TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_weekly_report_members_report
        FOREIGN KEY (weekly_report_id)
            REFERENCES weekly_reports(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_weekly_report_members_user
        FOREIGN KEY (user_id)
            REFERENCES user_accounts(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_weekly_report_members_report_user
    ON weekly_report_members(weekly_report_id, user_id);
