CREATE TABLE IF NOT EXISTS task_review_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    decision VARCHAR(30) NOT NULL,
    from_status VARCHAR(30) NOT NULL,
    to_status VARCHAR(30) NOT NULL,
    reason TEXT,
    code_insight_review_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_review_decisions_task
        FOREIGN KEY (task_id)
            REFERENCES tasks(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_task_review_decisions_reviewer
        FOREIGN KEY (reviewer_id)
            REFERENCES user_accounts(id),

    CONSTRAINT chk_task_review_decisions_decision
        CHECK (decision IN ('REQUEST_REVIEW', 'APPROVED', 'REJECTED')),

    CONSTRAINT chk_task_review_decisions_status
        CHECK (from_status IN ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED')
            AND to_status IN ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED'))
);

CREATE INDEX IF NOT EXISTS idx_task_review_decisions_task_created
    ON task_review_decisions(task_id, created_at DESC);
