-- =========================================================
-- RESOURCES
-- =========================================================

CREATE TYPE resource_type_enum AS ENUM (
    'FILE',
    'LINK'
);

CREATE TABLE resources (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           classroom_id BIGINT NOT NULL,
                           uploader_id BIGINT NOT NULL,
                           name VARCHAR(255) NOT NULL,
                           type resource_type_enum NOT NULL,
                           url VARCHAR NOT NULL,
                           file_size BIGINT,
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT fk_resources_classroom
                               FOREIGN KEY (classroom_id)
                                   REFERENCES academic_contexts(id)
                                   ON DELETE CASCADE,

                           CONSTRAINT fk_resources_uploader
                               FOREIGN KEY (uploader_id)
                                   REFERENCES user_accounts(id)
);
