ALTER TYPE task_status_enum ADD VALUE IF NOT EXISTS 'NEEDS_CHANGES';

ALTER TABLE project_code_insight_settings
    ADD COLUMN IF NOT EXISTS block_score_threshold INTEGER NOT NULL DEFAULT 50;

ALTER TABLE project_code_insight_settings
    DROP CONSTRAINT IF EXISTS chk_project_code_insight_settings_threshold,
    DROP CONSTRAINT IF EXISTS chk_project_code_insight_settings_thresholds;

ALTER TABLE project_code_insight_settings
    ADD CONSTRAINT chk_project_code_insight_settings_thresholds
        CHECK (
            min_score_warning_threshold BETWEEN 0 AND 100
            AND block_score_threshold BETWEEN 0 AND 100
            AND block_score_threshold < min_score_warning_threshold
        );

ALTER TABLE github_integrations
    ADD COLUMN IF NOT EXISTS webhook_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS webhook_events_json TEXT,
    ADD COLUMN IF NOT EXISTS webhook_last_synced_at TIMESTAMP;

ALTER TABLE task_review_decisions
    DROP CONSTRAINT IF EXISTS chk_task_review_decisions_decision;

ALTER TABLE task_review_decisions
    ADD CONSTRAINT chk_task_review_decisions_decision
        CHECK (decision IN ('REQUEST_REVIEW', 'APPROVED', 'REJECTED', 'REOPENED_REVIEW', 'REQUESTED_REWORK'));

ALTER TABLE task_review_decisions
    DROP CONSTRAINT IF EXISTS chk_task_review_decisions_status;

ALTER TABLE task_review_decisions
    ADD CONSTRAINT chk_task_review_decisions_status
        CHECK (from_status IN ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'NEEDS_CHANGES')
            AND to_status IN ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'NEEDS_CHANGES'));

CREATE TABLE IF NOT EXISTS code_insight_manual_evidence_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    evidence_type VARCHAR(30) NOT NULL,
    evidence_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    suggested_by BIGINT NOT NULL,
    confirmed_by BIGINT,
    reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_code_insight_manual_links_project
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_code_insight_manual_links_task
        FOREIGN KEY (task_id)
            REFERENCES tasks(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_code_insight_manual_links_suggested_by
        FOREIGN KEY (suggested_by)
            REFERENCES user_accounts(id),

    CONSTRAINT fk_code_insight_manual_links_confirmed_by
        FOREIGN KEY (confirmed_by)
            REFERENCES user_accounts(id),

    CONSTRAINT uk_code_insight_manual_links_target
        UNIQUE (project_id, task_id, evidence_type, evidence_id),

    CONSTRAINT chk_code_insight_manual_links_type
        CHECK (evidence_type IN ('COMMIT', 'PULL_REQUEST', 'CHECK_RUN')),

    CONSTRAINT chk_code_insight_manual_links_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED'))
);

CREATE INDEX IF NOT EXISTS idx_code_insight_manual_links_task
    ON code_insight_manual_evidence_links(task_id, status);

CREATE INDEX IF NOT EXISTS idx_code_insight_manual_links_project
    ON code_insight_manual_evidence_links(project_id, evidence_type, status);
