CREATE TABLE IF NOT EXISTS github_webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id BIGINT,
    delivery_id VARCHAR(120) NOT NULL UNIQUE,
    event_type VARCHAR(80) NOT NULL,
    signature VARCHAR(255),
    payload_hash VARCHAR(64) NOT NULL,
    payload_json JSONB NOT NULL,
    processed_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    error_message TEXT,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,

    CONSTRAINT fk_github_webhook_events_integration
        FOREIGN KEY (integration_id)
            REFERENCES github_integrations(id)
            ON DELETE SET NULL,

    CONSTRAINT chk_github_webhook_events_status
        CHECK (processed_status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'IGNORED'))
);

CREATE INDEX IF NOT EXISTS idx_github_webhook_events_integration_received
    ON github_webhook_events(integration_id, received_at DESC);

CREATE INDEX IF NOT EXISTS idx_github_webhook_events_status
    ON github_webhook_events(processed_status);

CREATE TABLE IF NOT EXISTS github_commits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    sha VARCHAR(64) NOT NULL,
    branch_name VARCHAR(255),
    message TEXT,
    author_name VARCHAR(255),
    author_email VARCHAR(255),
    author_login VARCHAR(255),
    committed_at TIMESTAMP,
    url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_github_commits_integration
        FOREIGN KEY (integration_id)
            REFERENCES github_integrations(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_github_commits_project
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE,

    CONSTRAINT uk_github_commits_integration_sha
        UNIQUE (integration_id, sha)
);

CREATE INDEX IF NOT EXISTS idx_github_commits_project_branch
    ON github_commits(project_id, branch_name);

CREATE TABLE IF NOT EXISTS github_pull_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    pr_number INTEGER NOT NULL,
    title VARCHAR(500),
    body TEXT,
    state VARCHAR(40),
    draft BOOLEAN NOT NULL DEFAULT FALSE,
    author_login VARCHAR(255),
    head_branch VARCHAR(255),
    base_branch VARCHAR(255),
    head_sha VARCHAR(64),
    merge_commit_sha VARCHAR(64),
    merged_at TIMESTAMP,
    url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_github_pull_requests_integration
        FOREIGN KEY (integration_id)
            REFERENCES github_integrations(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_github_pull_requests_project
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE,

    CONSTRAINT uk_github_pull_requests_integration_number
        UNIQUE (integration_id, pr_number)
);

CREATE INDEX IF NOT EXISTS idx_github_pull_requests_project_state
    ON github_pull_requests(project_id, state);

CREATE TABLE IF NOT EXISTS github_check_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    external_id VARCHAR(120) NOT NULL,
    sha VARCHAR(64),
    name VARCHAR(255),
    event_type VARCHAR(40) NOT NULL,
    status VARCHAR(80),
    conclusion VARCHAR(80),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_github_check_runs_integration
        FOREIGN KEY (integration_id)
            REFERENCES github_integrations(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_github_check_runs_project
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE,

    CONSTRAINT uk_github_check_runs_integration_event_external
        UNIQUE (integration_id, event_type, external_id)
);

CREATE INDEX IF NOT EXISTS idx_github_check_runs_project_sha
    ON github_check_runs(project_id, sha);
