ALTER TABLE test_runs
ADD COLUMN IF NOT EXISTS is_saved BOOLEAN DEFAULT FALSE;

ALTER TABLE test_executions
ADD COLUMN IF NOT EXISTS failed_step_index INTEGER,
ADD COLUMN IF NOT EXISTS evidence_urls JSONB;
