ALTER TABLE sprints
    ADD COLUMN IF NOT EXISTS capacity_hours DECIMAL(6,1);

ALTER TABLE sprints
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS sprint_plan_date DATE;
