-- Migration: V20260527224500__add_kanban_columns.sql
-- Date: 2026-05-27
-- Author: Codex
-- Description: Add project-scoped Kanban columns and link tasks to columns

CREATE TABLE IF NOT EXISTS kanban_columns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    status_key VARCHAR(50),
    color VARCHAR(80) NOT NULL DEFAULT 'bg-outline',
    column_order INTEGER NOT NULL DEFAULT 0,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_kanban_columns_project
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE,

    CONSTRAINT uq_kanban_columns_project_name
        UNIQUE (project_id, name),

    CONSTRAINT uq_kanban_columns_project_status_key
        UNIQUE (project_id, status_key)
);

CREATE INDEX IF NOT EXISTS idx_kanban_columns_project_order
    ON kanban_columns(project_id, is_archived, column_order, id);

INSERT INTO kanban_columns (project_id, name, status_key, color, column_order, is_default)
SELECT p.id, defaults.name, defaults.status_key, defaults.color, defaults.column_order, TRUE
FROM projects p
CROSS JOIN (
    VALUES
        ('Todo', 'TODO', 'bg-outline', 0),
        ('In Progress', 'IN_PROGRESS', 'bg-primary', 1),
        ('In Review', 'IN_REVIEW', 'bg-[#a855f7]', 2),
        ('Done', 'DONE', 'bg-[#16a34a]', 3),
        ('Blocked', 'BLOCKED', 'bg-error', 4)
) AS defaults(name, status_key, color, column_order)
ON CONFLICT (project_id, status_key) DO NOTHING;

ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS column_id BIGINT;

ALTER TABLE tasks
    ADD CONSTRAINT fk_tasks_kanban_column
        FOREIGN KEY (column_id)
            REFERENCES kanban_columns(id)
            ON DELETE SET NULL;

UPDATE tasks t
SET column_id = kc.id
FROM kanban_columns kc
WHERE kc.project_id = t.project_id
  AND kc.status_key = t.status::text
  AND t.column_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_tasks_project_column
    ON tasks(project_id, column_id);
