-- =========================================================
-- Task Comments & Likes (Discussion Module)
-- =========================================================

CREATE TABLE task_comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT NOT NULL,
    content     TEXT NOT NULL,
    created_by  BIGINT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_comments_task
        FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,

    CONSTRAINT fk_task_comments_user
        FOREIGN KEY (created_by) REFERENCES user_accounts(id)
);

CREATE TABLE task_comment_votes (
    comment_id  BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    is_upvote   BOOLEAN NOT NULL DEFAULT TRUE, -- TRUE = upvote, FALSE = downvote

    PRIMARY KEY (comment_id, user_id),

    CONSTRAINT fk_task_comment_votes_comment
        FOREIGN KEY (comment_id) REFERENCES task_comments(id) ON DELETE CASCADE,

    CONSTRAINT fk_task_comment_votes_user
        FOREIGN KEY (user_id) REFERENCES user_accounts(id) ON DELETE CASCADE
);
