-- Add new task type
ALTER TYPE task_type_enum ADD VALUE IF NOT EXISTS 'MODULE_TASK';

-- Create Business Modules table
CREATE TABLE IF NOT EXISTS business_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_business_modules_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

-- Update Use Cases
ALTER TABLE use_cases ADD COLUMN module_id BIGINT;
ALTER TABLE use_cases ADD CONSTRAINT fk_use_cases_module FOREIGN KEY (module_id) REFERENCES business_modules(id);

ALTER TABLE use_cases ALTER COLUMN requirement_id DROP NOT NULL;

-- Create Mapping Table Requirement <-> UseCase
CREATE TABLE IF NOT EXISTS requirement_use_cases (
    use_case_id BIGINT NOT NULL,
    requirement_id BIGINT NOT NULL,
    PRIMARY KEY (use_case_id, requirement_id),
    CONSTRAINT fk_ruc_use_case FOREIGN KEY (use_case_id) REFERENCES use_cases(id),
    CONSTRAINT fk_ruc_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

-- Backfill data to mapping table
INSERT INTO requirement_use_cases (use_case_id, requirement_id)
SELECT id, requirement_id FROM use_cases WHERE requirement_id IS NOT NULL 
ON CONFLICT DO NOTHING;

-- Update Tasks
ALTER TABLE tasks ADD COLUMN module_id BIGINT;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_module FOREIGN KEY (module_id) REFERENCES business_modules(id);
