-- =========================================================
-- ENUM TYPES
-- =========================================================

CREATE TYPE project_type_enum AS ENUM (
    'WEB_APP',
    'MOBILE',
    'DATABASE',
    'RESEARCH',
    'OTHER'
);

CREATE TYPE project_status_enum AS ENUM (
    'PLANNING',
    'ACTIVE',
    'IN_REVIEW',
    'COMPLETED',
    'ARCHIVED'
);

CREATE TYPE sprint_status_enum AS ENUM (
    'PLANNED',
    'ACTIVE',
    'COMPLETED'
);

CREATE TYPE requirement_type_enum AS ENUM (
    'FUNCTIONAL',
    'NON_FUNCTIONAL'
);

CREATE TYPE priority_enum AS ENUM (
    'CRITICAL',
    'HIGH',
    'MEDIUM',
    'LOW'
);

CREATE TYPE requirement_status_enum AS ENUM (
    'DRAFT',
    'IN_PROGRESS',
    'IN_REVIEW',
    'DONE',
    'DEPRECATED'
);

CREATE TYPE task_type_enum AS ENUM (
    'DEVELOPMENT',
    'TESTING',
    'DOCUMENTATION',
    'UI_UX',
    'RESEARCH',
    'DEPLOYMENT',
    'BUG_FIX',
    'REVIEW'
);

CREATE TYPE task_status_enum AS ENUM (
    'TODO',
    'IN_PROGRESS',
    'IN_REVIEW',
    'DONE',
    'BLOCKED'
);

CREATE TYPE test_type_enum AS ENUM (
    'UNIT',
    'INTEGRATION',
    'UI',
    'API',
    'MANUAL'
);

CREATE TYPE test_case_status_enum AS ENUM (
    'NOT_RUN',
    'PASS',
    'FAIL',
    'BLOCKED'
);

CREATE TYPE test_execution_status_enum AS ENUM (
    'PASS',
    'FAIL',
    'BLOCKED'
);

CREATE TYPE environment_enum AS ENUM (
    'DEV',
    'STAGING'
);

CREATE TYPE bug_severity_enum AS ENUM (
    'CRITICAL',
    'HIGH',
    'MEDIUM',
    'LOW'
);

CREATE TYPE bug_status_enum AS ENUM (
    'OPEN',
    'IN_PROGRESS',
    'FIXED',
    'VERIFIED',
    'CLOSED',
    'REOPENED'
);

CREATE TYPE evidence_type_enum AS ENUM (
    'SCREENSHOT',
    'SCREEN_RECORDING',
    'GITHUB_COMMIT',
    'API_RESPONSE',
    'FIGMA_LINK',
    'TEST_RESULT',
    'DB_DIAGRAM',
    'DEPLOY_LINK',
    'SURVEY',
    'DOCUMENT'
);

CREATE TYPE evidence_status_enum AS ENUM (
    'PENDING',
    'AUTO_CHECKED',
    'ACCEPTED',
    'REJECTED',
    'NEEDS_CLARIFICATION'
);

CREATE TYPE evidence_entity_type_enum AS ENUM (
    'REQUIREMENT',
    'TASK',
    'TEST_CASE',
    'BUG_REPORT',
    'SPRINT'
);

CREATE TYPE ai_generation_type_enum AS ENUM (
    'GENERATE_TASK',
    'SUGGEST_TEST',
    'WEEKLY_REPORT',
    'REQUIREMENT_IMPORT',
    'MISSING_ARTIFACT',
    'CONTRIBUTION_SUMMARY'
);

CREATE TYPE mentor_comment_entity_type_enum AS ENUM (
    'REQUIREMENT',
    'WEEKLY_REPORT',
    'TASK'
);

CREATE TYPE notification_type_enum AS ENUM (
    'TASK_ASSIGNED',
    'TASK_COMMENTED',
    'DEADLINE_NEAR',
    'TEST_FAILED',
    'AI_ALERT',
    'MENTOR_COMMENT'
);

-- =========================================================
-- AUTH & USER
-- =========================================================

CREATE TABLE system_roles (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(50) NOT NULL UNIQUE,
                              description VARCHAR(255)
);

CREATE TABLE project_roles (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR(50) NOT NULL UNIQUE,
                               description VARCHAR(255)
);

CREATE TABLE user_accounts (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               username VARCHAR(50) NOT NULL UNIQUE,
                               email VARCHAR(255) NOT NULL UNIQUE,
                               password_hash VARCHAR NOT NULL,
                               system_role_id BIGINT NOT NULL,
                               is_active BOOLEAN NOT NULL DEFAULT TRUE,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_user_accounts_system_role
                                   FOREIGN KEY (system_role_id)
                                       REFERENCES system_roles(id)
);

CREATE TABLE user_profiles (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL UNIQUE,
                               full_name VARCHAR(100),
                               avatar_url VARCHAR,
                               bio TEXT,
                               phone VARCHAR(20),
                               updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_user_profiles_user
                                   FOREIGN KEY (user_id)
                                       REFERENCES user_accounts(id)
                                       ON DELETE CASCADE
);

-- =========================================================
-- PROJECT & SPRINT
-- =========================================================

CREATE TABLE academic_contexts (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   subject VARCHAR(100) NOT NULL,
                                   semester VARCHAR(20) NOT NULL,
                                   academic_year VARCHAR(10) NOT NULL,

                                   CONSTRAINT uq_academic_contexts_subject_semester_year
                                       UNIQUE (subject, semester, academic_year)
);

CREATE TABLE projects (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          description TEXT,
                          type project_type_enum NOT NULL,
                          academic_context_id BIGINT,
                          start_date DATE,
                          deadline DATE NOT NULL,
                          status project_status_enum NOT NULL DEFAULT 'PLANNING',
                          color VARCHAR(7),
                          avatar_url VARCHAR,
                          created_by BIGINT NOT NULL,
                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_projects_academic_context
                              FOREIGN KEY (academic_context_id)
                                  REFERENCES academic_contexts(id),

                          CONSTRAINT fk_projects_created_by
                              FOREIGN KEY (created_by)
                                  REFERENCES user_accounts(id)
);

CREATE TABLE project_members (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 project_id BIGINT NOT NULL,
                                 user_id BIGINT NOT NULL,
                                 project_role_id BIGINT NOT NULL,
                                 joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 invited_by BIGINT,

                                 CONSTRAINT fk_project_members_project
                                     FOREIGN KEY (project_id)
                                         REFERENCES projects(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT fk_project_members_user
                                     FOREIGN KEY (user_id)
                                         REFERENCES user_accounts(id),

                                 CONSTRAINT fk_project_members_role
                                     FOREIGN KEY (project_role_id)
                                         REFERENCES project_roles(id),

                                 CONSTRAINT fk_project_members_invited_by
                                     FOREIGN KEY (invited_by)
                                         REFERENCES user_accounts(id),

                                 CONSTRAINT uq_project_members_project_user
                                     UNIQUE (project_id, user_id)
);

CREATE TABLE invitation_links (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  project_id BIGINT NOT NULL,
                                  token VARCHAR(64) NOT NULL UNIQUE,
                                  project_role_id BIGINT NOT NULL,
                                  expires_at TIMESTAMP NOT NULL,
                                  created_by BIGINT NOT NULL,
                                  used_by BIGINT,
                                  used_at TIMESTAMP,

                                  CONSTRAINT fk_invitation_links_project
                                      FOREIGN KEY (project_id)
                                          REFERENCES projects(id)
                                          ON DELETE CASCADE,

                                  CONSTRAINT fk_invitation_links_role
                                      FOREIGN KEY (project_role_id)
                                          REFERENCES project_roles(id),

                                  CONSTRAINT fk_invitation_links_created_by
                                      FOREIGN KEY (created_by)
                                          REFERENCES user_accounts(id),

                                  CONSTRAINT fk_invitation_links_used_by
                                      FOREIGN KEY (used_by)
                                          REFERENCES user_accounts(id)
);

CREATE TABLE sprints (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         project_id BIGINT NOT NULL,
                         name VARCHAR(100) NOT NULL,
                         goal TEXT,
                         start_date DATE NOT NULL,
                         end_date DATE NOT NULL,
                         status sprint_status_enum NOT NULL DEFAULT 'PLANNED',
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_sprints_project
                             FOREIGN KEY (project_id)
                                 REFERENCES projects(id)
                                 ON DELETE CASCADE,

                         CONSTRAINT ck_sprints_date_range
                             CHECK (end_date >= start_date)
);

CREATE TABLE rtm_snapshots (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               project_id BIGINT NOT NULL,
                               sprint_id BIGINT NOT NULL,
                               snapshot_data JSONB NOT NULL,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_rtm_snapshots_project
                                   FOREIGN KEY (project_id)
                                       REFERENCES projects(id)
                                       ON DELETE CASCADE,

                               CONSTRAINT fk_rtm_snapshots_sprint
                                   FOREIGN KEY (sprint_id)
                                       REFERENCES sprints(id)
                                       ON DELETE CASCADE
);

CREATE TABLE shareable_links (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 project_id BIGINT NOT NULL,
                                 created_by BIGINT NOT NULL,
                                 token VARCHAR(64) NOT NULL UNIQUE,
                                 expires_at TIMESTAMP,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_shareable_links_project
                                     FOREIGN KEY (project_id)
                                         REFERENCES projects(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT fk_shareable_links_created_by
                                     FOREIGN KEY (created_by)
                                         REFERENCES user_accounts(id)
);

-- =========================================================
-- REQUIREMENT & USE CASE
-- =========================================================

CREATE TABLE requirements (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              project_id BIGINT NOT NULL,
                              title VARCHAR(200) NOT NULL,
                              description TEXT,
                              type requirement_type_enum NOT NULL,
                              priority priority_enum NOT NULL,
                              acceptance_criteria JSONB NOT NULL,
                              owner_id BIGINT,
                              status requirement_status_enum NOT NULL DEFAULT 'DRAFT',
                              evidence_required BOOLEAN NOT NULL DEFAULT FALSE,
                              req_order INT,
                              created_by BIGINT NOT NULL,
                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              CONSTRAINT fk_requirements_project
                                  FOREIGN KEY (project_id)
                                      REFERENCES projects(id)
                                      ON DELETE CASCADE,

                              CONSTRAINT fk_requirements_owner
                                  FOREIGN KEY (owner_id)
                                      REFERENCES user_accounts(id),

                              CONSTRAINT fk_requirements_created_by
                                  FOREIGN KEY (created_by)
                                      REFERENCES user_accounts(id)
);

CREATE TABLE requirement_tags (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  requirement_id BIGINT NOT NULL,
                                  tag VARCHAR(50) NOT NULL,

                                  CONSTRAINT fk_requirement_tags_requirement
                                      FOREIGN KEY (requirement_id)
                                          REFERENCES requirements(id)
                                          ON DELETE CASCADE,

                                  CONSTRAINT uq_requirement_tags_requirement_tag
                                      UNIQUE (requirement_id, tag)
);

CREATE TABLE use_cases (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           requirement_id BIGINT NOT NULL,
                           name VARCHAR(200) NOT NULL,
                           precondition TEXT,
                           postcondition TEXT,
                           main_flow JSONB NOT NULL,
                           alternative_flow JSONB,
                           created_by BIGINT NOT NULL,
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT fk_use_cases_requirement
                               FOREIGN KEY (requirement_id)
                                   REFERENCES requirements(id)
                                   ON DELETE CASCADE,

                           CONSTRAINT fk_use_cases_created_by
                               FOREIGN KEY (created_by)
                                   REFERENCES user_accounts(id)
);

CREATE TABLE use_case_actors (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 use_case_id BIGINT NOT NULL,
                                 actor_name VARCHAR(100) NOT NULL,

                                 CONSTRAINT fk_use_case_actors_use_case
                                     FOREIGN KEY (use_case_id)
                                         REFERENCES use_cases(id)
                                         ON DELETE CASCADE
);

-- =========================================================
-- TASK
-- =========================================================

CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       project_id BIGINT NOT NULL,
                       requirement_id BIGINT,
                       sprint_id BIGINT,
                       title VARCHAR(200) NOT NULL,
                       description TEXT,
                       type task_type_enum NOT NULL,
                       primary_assignee_id BIGINT,
                       priority priority_enum NOT NULL,
                       deadline DATE,
                       estimated_hours DECIMAL(5,1),
                       status task_status_enum NOT NULL DEFAULT 'TODO',
                       blocked_reason TEXT,
                       created_by BIGINT NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT fk_tasks_project
                           FOREIGN KEY (project_id)
                               REFERENCES projects(id)
                               ON DELETE CASCADE,

                       CONSTRAINT fk_tasks_requirement
                           FOREIGN KEY (requirement_id)
                               REFERENCES requirements(id)
                               ON DELETE SET NULL,

                       CONSTRAINT fk_tasks_sprint
                           FOREIGN KEY (sprint_id)
                               REFERENCES sprints(id)
                               ON DELETE SET NULL,

                       CONSTRAINT fk_tasks_primary_assignee
                           FOREIGN KEY (primary_assignee_id)
                               REFERENCES user_accounts(id),

                       CONSTRAINT fk_tasks_created_by
                           FOREIGN KEY (created_by)
                               REFERENCES user_accounts(id)
);

CREATE TABLE task_assignees (
                                task_id BIGINT NOT NULL,
                                user_id BIGINT NOT NULL,

                                PRIMARY KEY (task_id, user_id),

                                CONSTRAINT fk_task_assignees_task
                                    FOREIGN KEY (task_id)
                                        REFERENCES tasks(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_task_assignees_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES user_accounts(id)
);

CREATE TABLE task_checklists (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 task_id BIGINT NOT NULL,
                                 content VARCHAR(500) NOT NULL,
                                 is_done BOOLEAN NOT NULL DEFAULT FALSE,
                                 order_index INT NOT NULL DEFAULT 0,

                                 CONSTRAINT fk_task_checklists_task
                                     FOREIGN KEY (task_id)
                                         REFERENCES tasks(id)
                                         ON DELETE CASCADE
);

CREATE TABLE task_dependencies (
                                   blocking_task_id BIGINT NOT NULL,
                                   blocked_task_id BIGINT NOT NULL,

                                   PRIMARY KEY (blocking_task_id, blocked_task_id),

                                   CONSTRAINT fk_task_dependencies_blocking_task
                                       FOREIGN KEY (blocking_task_id)
                                           REFERENCES tasks(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT fk_task_dependencies_blocked_task
                                       FOREIGN KEY (blocked_task_id)
                                           REFERENCES tasks(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT ck_task_dependencies_not_self
                                       CHECK (blocking_task_id <> blocked_task_id)
);

-- =========================================================
-- TEST CASE & BUG
-- =========================================================

CREATE TABLE test_cases (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            project_id BIGINT NOT NULL,
                            requirement_id BIGINT NOT NULL,
                            title VARCHAR(200) NOT NULL,
                            type test_type_enum NOT NULL,
                            precondition TEXT,
                            expected_result TEXT NOT NULL,
                            status test_case_status_enum NOT NULL DEFAULT 'NOT_RUN',
                            created_by BIGINT NOT NULL,
                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT fk_test_cases_project
                                FOREIGN KEY (project_id)
                                    REFERENCES projects(id)
                                    ON DELETE CASCADE,

                            CONSTRAINT fk_test_cases_requirement
                                FOREIGN KEY (requirement_id)
                                    REFERENCES requirements(id)
                                    ON DELETE CASCADE,

                            CONSTRAINT fk_test_cases_created_by
                                FOREIGN KEY (created_by)
                                    REFERENCES user_accounts(id)
);

CREATE TABLE test_steps (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            test_case_id BIGINT NOT NULL,
                            step_number INT NOT NULL,
                            description TEXT NOT NULL,

                            CONSTRAINT fk_test_steps_test_case
                                FOREIGN KEY (test_case_id)
                                    REFERENCES test_cases(id)
                                    ON DELETE CASCADE,

                            CONSTRAINT uq_test_steps_test_case_step
                                UNIQUE (test_case_id, step_number)
);

CREATE TABLE test_executions (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 test_case_id BIGINT NOT NULL,
                                 executed_by BIGINT NOT NULL,
                                 executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 status test_execution_status_enum NOT NULL,
                                 actual_result TEXT,
                                 environment environment_enum NOT NULL,

                                 CONSTRAINT fk_test_executions_test_case
                                     FOREIGN KEY (test_case_id)
                                         REFERENCES test_cases(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT fk_test_executions_executed_by
                                     FOREIGN KEY (executed_by)
                                         REFERENCES user_accounts(id)
);

CREATE TABLE bug_reports (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             project_id BIGINT NOT NULL,
                             test_execution_id BIGINT,
                             title VARCHAR(200) NOT NULL,
                             description TEXT,
                             severity bug_severity_enum NOT NULL,
                             environment environment_enum,
                             steps_to_reproduce JSONB,
                             expected_result TEXT,
                             actual_result TEXT,
                             status bug_status_enum NOT NULL DEFAULT 'OPEN',
                             assigned_to BIGINT,
                             fix_commit_hash VARCHAR(40),
                             related_task_id BIGINT,
                             created_by BIGINT NOT NULL,
                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT fk_bug_reports_project
                                 FOREIGN KEY (project_id)
                                     REFERENCES projects(id)
                                     ON DELETE CASCADE,

                             CONSTRAINT fk_bug_reports_test_execution
                                 FOREIGN KEY (test_execution_id)
                                     REFERENCES test_executions(id)
                                     ON DELETE SET NULL,

                             CONSTRAINT fk_bug_reports_assigned_to
                                 FOREIGN KEY (assigned_to)
                                     REFERENCES user_accounts(id),

                             CONSTRAINT fk_bug_reports_related_task
                                 FOREIGN KEY (related_task_id)
                                     REFERENCES tasks(id)
                                     ON DELETE SET NULL,

                             CONSTRAINT fk_bug_reports_created_by
                                 FOREIGN KEY (created_by)
                                     REFERENCES user_accounts(id)
);

-- =========================================================
-- EVIDENCE
-- =========================================================

CREATE TABLE evidence (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          project_id BIGINT NOT NULL,
                          uploaded_by BIGINT NOT NULL,
                          type evidence_type_enum NOT NULL,
                          title VARCHAR(200) NOT NULL,
                          description TEXT,
                          file_url VARCHAR,
                          external_url VARCHAR,
                          metadata JSONB,
                          status evidence_status_enum NOT NULL DEFAULT 'PENDING',
                          reviewed_by BIGINT,
                          reviewed_at TIMESTAMP,
                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_evidence_project
                              FOREIGN KEY (project_id)
                                  REFERENCES projects(id)
                                  ON DELETE CASCADE,

                          CONSTRAINT fk_evidence_uploaded_by
                              FOREIGN KEY (uploaded_by)
                                  REFERENCES user_accounts(id),

                          CONSTRAINT fk_evidence_reviewed_by
                              FOREIGN KEY (reviewed_by)
                                  REFERENCES user_accounts(id)
);

CREATE TABLE evidence_links (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                evidence_id BIGINT NOT NULL,
                                entity_type evidence_entity_type_enum NOT NULL,
                                entity_id BIGINT NOT NULL,
                                linked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_evidence_links_evidence
                                    FOREIGN KEY (evidence_id)
                                        REFERENCES evidence(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT uq_evidence_links_evidence_entity
                                    UNIQUE (evidence_id, entity_type, entity_id)
);

-- =========================================================
-- AI & REPORTING
-- =========================================================

CREATE TABLE ai_generation_cache (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     project_id BIGINT NOT NULL,
                                     type ai_generation_type_enum NOT NULL,
                                     input_hash VARCHAR(64) NOT NULL,
                                     input_data JSONB NOT NULL,
                                     output_data JSONB NOT NULL,
                                     model_used VARCHAR(50) NOT NULL,
                                     tokens_used INT,
                                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     expires_at TIMESTAMP NOT NULL,

                                     CONSTRAINT fk_ai_generation_cache_project
                                         FOREIGN KEY (project_id)
                                             REFERENCES projects(id)
                                             ON DELETE CASCADE,

                                     CONSTRAINT uq_ai_generation_cache_type_input_hash
                                         UNIQUE (type, input_hash)
);

CREATE TABLE weekly_reports (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                project_id BIGINT NOT NULL,
                                sprint_id BIGINT,
                                week_number INT NOT NULL,
                                generated_by BIGINT,
                                content_markdown TEXT NOT NULL,
                                input_snapshot JSONB NOT NULL,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_weekly_reports_project
                                    FOREIGN KEY (project_id)
                                        REFERENCES projects(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_weekly_reports_sprint
                                    FOREIGN KEY (sprint_id)
                                        REFERENCES sprints(id)
                                        ON DELETE SET NULL,

                                CONSTRAINT fk_weekly_reports_generated_by
                                    FOREIGN KEY (generated_by)
                                        REFERENCES user_accounts(id)
);

CREATE TABLE mentor_comments (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 project_id BIGINT NOT NULL,
                                 commenter_id BIGINT NOT NULL,
                                 entity_type mentor_comment_entity_type_enum NOT NULL,
                                 entity_id BIGINT NOT NULL,
                                 content TEXT NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_mentor_comments_project
                                     FOREIGN KEY (project_id)
                                         REFERENCES projects(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT fk_mentor_comments_commenter
                                     FOREIGN KEY (commenter_id)
                                         REFERENCES user_accounts(id)
);

CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               project_id BIGINT,
                               type notification_type_enum NOT NULL,
                               title VARCHAR(200) NOT NULL,
                               message TEXT,
                               entity_type VARCHAR(50),
                               entity_id BIGINT,
                               is_read BOOLEAN NOT NULL DEFAULT FALSE,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_notifications_user
                                   FOREIGN KEY (user_id)
                                       REFERENCES user_accounts(id)
                                       ON DELETE CASCADE,

                               CONSTRAINT fk_notifications_project
                                   FOREIGN KEY (project_id)
                                       REFERENCES projects(id)
                                       ON DELETE CASCADE
);

-- =========================================================
-- CODE INSIGHT
-- =========================================================

CREATE TABLE github_integrations (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     project_id BIGINT NOT NULL UNIQUE,
                                     repo_owner VARCHAR(100) NOT NULL,
                                     repo_name VARCHAR(100) NOT NULL,
                                     access_token_encrypted TEXT NOT NULL,
                                     webhook_secret VARCHAR NOT NULL,
                                     connected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     connected_by BIGINT NOT NULL,

                                     CONSTRAINT fk_github_integrations_project
                                         FOREIGN KEY (project_id)
                                             REFERENCES projects(id)
                                             ON DELETE CASCADE,

                                     CONSTRAINT fk_github_integrations_connected_by
                                         FOREIGN KEY (connected_by)
                                             REFERENCES user_accounts(id)
);

CREATE TABLE commit_metrics (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                project_id BIGINT NOT NULL,
                                user_id BIGINT,
                                github_username VARCHAR(100) NOT NULL,
                                commit_sha VARCHAR(40) NOT NULL UNIQUE,
                                commit_message TEXT NOT NULL,
                                committed_at TIMESTAMP NOT NULL,
                                files_changed INT,
                                lines_added INT,
                                lines_deleted INT,
                                task_id BIGINT,
                                sprint_id BIGINT,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_commit_metrics_project
                                    FOREIGN KEY (project_id)
                                        REFERENCES projects(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_commit_metrics_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES user_accounts(id),

                                CONSTRAINT fk_commit_metrics_task
                                    FOREIGN KEY (task_id)
                                        REFERENCES tasks(id)
                                        ON DELETE SET NULL,

                                CONSTRAINT fk_commit_metrics_sprint
                                    FOREIGN KEY (sprint_id)
                                        REFERENCES sprints(id)
                                        ON DELETE SET NULL
);

CREATE TABLE commit_quality_analysis (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         commit_id BIGINT NOT NULL UNIQUE,
                                         message_quality_score DECIMAL(3,2) NOT NULL,
                                         quality_flags JSONB,
                                         analyzed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                         CONSTRAINT fk_commit_quality_analysis_commit
                                             FOREIGN KEY (commit_id)
                                                 REFERENCES commit_metrics(id)
                                                 ON DELETE CASCADE,

                                         CONSTRAINT ck_commit_quality_score_range
                                             CHECK (message_quality_score >= 0.00 AND message_quality_score <= 1.00)
);

