-- Thêm cột verify_status vào bảng user_accounts
ALTER TABLE user_accounts ADD COLUMN IF NOT EXISTS verify_status VARCHAR(50) NOT NULL DEFAULT 'UNVERIFIED';

-- Tạo bảng mentor_verification_requests
CREATE TABLE IF NOT EXISTS mentor_verification_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    card_image_url VARCHAR NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    rejection_reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by BIGINT,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_verification_user FOREIGN KEY (user_id) REFERENCES user_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_verification_resolver FOREIGN KEY (resolved_by) REFERENCES user_accounts(id) ON DELETE SET NULL
);

-- Bổ sung owner_id vào academic_contexts để phân quyền tự động cho người tạo không gian
ALTER TABLE academic_contexts ADD COLUMN IF NOT EXISTS owner_id BIGINT;
ALTER TABLE academic_contexts ADD CONSTRAINT fk_academic_context_owner FOREIGN KEY (owner_id) REFERENCES user_accounts(id) ON DELETE SET NULL;



