spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/dev_track_ai
    username: postgres
    password: 30042005
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    out-of-order: true
