import React from 'react';

const LandingDashboard = () => {
  return (
    <>
<section id="dashboard" className="tint-b" style={{"padding":"72px 56px","background":"#fff","overflow":"hidden"}}>
                        <div className="wrap">
                            <div style={{"display":"flex","justifyContent":"space-between","alignItems":"flex-end"}}>
                                <div><div className="s-eye sr"><div className="s-el"></div></div><div className="sb sr">🖥 Live Dashboard</div><h2 className="st sr">Project health<br /><span style={{"color":"var(--t)"}}>at a glance</span></h2></div>
                                <div style={{"textAlign":"right"}} className="sr"><div style={{"fontSize":"11px","color":"var(--g400)","marginBottom":"4px"}}>Overall health</div><div style={{"fontSize":"52px","fontWeight":"900","color":"var(--t)","letterSpacing":"-3px","lineHeight":"1"}}>87</div><div style={{"fontSize":"11px","color":"var(--green)","fontWeight":"600"}}>↑ 4 pts this sprint</div></div>
                            </div>
                            <div className="dash-frame sr">
                                <div className="dtb"><div className="tls"><div className="tl tlr"></div><div className="tl tly"></div><div className="tl tlg"></div></div><div className="dttl">DevTrack AI — Mentor Dashboard</div><div className="dtabs"><div className="dtab a">Overview</div><div className="dtab">Requirements</div><div className="dtab">Traceability</div><div className="dtab">Audit</div></div></div>
                                <div className="dbd">
                                    <div className="dl"><div className="hs"><div style={{"fontSize":"9px","opacity":".7","textTransform":"uppercase","letterSpacing":"1px","marginBottom":"4px"}}>Project Health</div><div className="hsn">87</div><div className="hsl">Excellent</div></div><div className="hbw"><div className="hbr"><div className="hbt"><span>Requirements</span><span>90%</span></div><div className="hbtr"><div className="hbf hft" style={{"width":"90%"}}></div></div></div><div className="hbr"><div className="hbt"><span>Tasks done</span><span>65%</span></div><div className="hbtr"><div className="hbf hfg" style={{"width":"65%"}}></div></div></div><div className="hbr"><div className="hbt"><span>Test pass</span><span>92%</span></div><div className="hbtr"><div className="hbf hfp" style={{"width":"92%"}}></div></div></div><div className="hbr"><div className="hbt"><span>Evidence</span><span>78%</span></div><div className="hbtr"><div className="hbf hfa" style={{"width":"78%"}}></div></div></div><div className="hbr"><div className="hbt"><span>Traceability</span><span>85%</span></div><div className="hbtr"><div className="hbf hft" style={{"width":"85%"}}></div></div></div></div><div style={{"marginTop":"14px","paddingTop":"12px","borderTop":"1px solid var(--g100)"}}><div style={{"fontSize":"9px","fontWeight":"700","color":"var(--g400)","textTransform":"uppercase","letterSpacing":".4px","marginBottom":"8px"}}>Team</div><div style={{"display":"flex","flexDirection":"column","gap":"6px"}}><div style={{"display":"flex","alignItems":"center","gap":"7px","fontSize":"9.5px","color":"var(--g600)"}}><div style={{"width":"20px","height":"20px","borderRadius":"50%","background":"var(--t)","color":"#fff","display":"flex","alignItems":"center","justifyContent":"center","fontSize":"8px","fontWeight":"700","flexShrink":"0"}}>KH</div>Khanh <span style={{"color":"var(--t)","fontWeight":"700"}}>(Leader)</span></div><div style={{"display":"flex","alignItems":"center","gap":"7px","fontSize":"9.5px","color":"var(--g600)"}}><div style={{"width":"20px","height":"20px","borderRadius":"50%","background":"var(--green)","color":"#fff","display":"flex","alignItems":"center","justifyContent":"center","fontSize":"8px","fontWeight":"700","flexShrink":"0"}}>NT</div>Nam Tran</div><div style={{"display":"flex","alignItems":"center","gap":"7px","fontSize":"9.5px","color":"var(--g600)"}}><div style={{"width":"20px","height":"20px","borderRadius":"50%","background":"var(--purple)","color":"#fff","display":"flex","alignItems":"center","justifyContent":"center","fontSize":"8px","fontWeight":"700","flexShrink":"0"}}>TL</div>Thien Le</div></div></div></div>
                                    <div className="dctr"><div className="dcr"><div className="mmc"><div className="mv">24</div><div className="ml">Requirements</div></div><div className="mmc"><div className="mv" style={{"color":"var(--t)"}}>31/48</div><div className="ml">Tasks</div></div><div className="mmc"><div className="mv" style={{"color":"var(--green)"}}>92%</div><div className="ml">Test pass</div></div></div><div className="sch"><div className="scht">Sprint velocity</div><div className="schb"><div className="schg"><div className="schbar bt" style={{"height":"55%"}}></div><div className="schbar bp" style={{"height":"75%"}}></div></div><div className="schg"><div className="schbar bt" style={{"height":"70%"}}></div><div className="schbar bp" style={{"height":"80%"}}></div></div><div className="schg"><div className="schbar bt" style={{"height":"62%"}}></div><div className="schbar bp" style={{"height":"70%"}}></div></div><div className="schg"><div className="schbar bt" style={{"height":"85%"}}></div><div className="schbar bp" style={{"height":"85%"}}></div></div><div className="schg"><div className="schbar bt" style={{"height":"78%"}}></div><div className="schbar bp" style={{"height":"90%"}}></div></div><div className="schg"><div className="schbar bt" style={{"height":"65%"}}></div><div className="schbar bp" style={{"height":"100%"}}></div></div></div></div><div className="dkb"><div className="dkc"><div className="dkh">To Do</div><div className="dkt"></div><div className="dkt"></div></div><div className="dkc"><div className="dkh">In Progress</div><div className="dkt tc"></div><div className="dkt tc"></div></div><div className="dkc"><div className="dkh">Review</div><div className="dkt ta"></div></div><div className="dkc"><div className="dkh">Done</div><div className="dkt tg"></div><div className="dkt tg"></div><div className="dkt tg"></div></div></div></div>
                                    <div className="dr"><div className="aic"><div className="aich"><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M9.663 17h4.673M12 3v1m6.364 1.636-.707.707M21 12h-1M4 12H3m1.343-5.657-.707-.707m2.828 9.9a5 5 0 1 1 7.072 0l-.548.547A3.374 3.374 0 0 0 14 18.469V19a2 2 0 1 1-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg> AI Insights</div><div className="aii"><div className="aib"></div>Velocity 23% below. Reassign Task-031.</div><div className="aii"><div className="aib"></div>PR #14 score 52/100 — needs rework.</div><div className="aii"><div className="aib"></div>3 requirements lack test coverage.</div><div className="aii"><div className="aib"></div>5 tasks missing evidence.</div></div><div className="rtm"><div className="rtmh">Traceability Matrix</div><div className="rtmr"><div className="rd" style={{"background":"var(--t)"}}></div>REQ-001 Login<div className="rs rsd">DONE</div></div><div className="rtmr"><div className="rd" style={{"background":"var(--t)"}}></div>REQ-002 Register<div className="rs rsd">DONE</div></div><div className="rtmr"><div className="rd" style={{"background":"var(--amber)"}}></div>REQ-003 Cart<div className="rs rsw">WIP</div></div><div className="rtmr"><div className="rd" style={{"background":"var(--red)"}}></div>REQ-007 Payment<div className="rs rsm">MISS</div></div></div><div style={{"background":"rgba(34,197,94,.05)","border":"1px solid rgba(34,197,94,.15)","borderRadius":"9px","padding":"10px"}}><div style={{"fontSize":"9px","fontWeight":"700","color":"var(--green)","textTransform":"uppercase","letterSpacing":".5px","marginBottom":"6px"}}>Evidence 78%</div><div style={{"display":"flex","alignItems":"center","gap":"6px"}}><div style={{"flex":"1","height":"5px","background":"var(--g100)","borderRadius":"100px","overflow":"hidden"}}><div style={{"width":"78%","height":"100%","background":"linear-gradient(90deg,var(--green),#16a34a)","borderRadius":"100px"}}></div></div><div style={{"fontSize":"10px","fontWeight":"700","color":"var(--green)"}}>37/48</div></div></div></div>
                                </div>
                            </div>
                        </div>
                    </section>
    </>
  );
};

export default LandingDashboard;
