import React from 'react';

const LandingGallery = () => {
  return (
    <>
<section id="gallery" className="tint-c" style={{"background":"var(--g50)","padding":"72px 0 60px","overflow":"hidden"}}>
                                        <div style={{"textAlign":"center","marginBottom":"36px","padding":"0 56px"}}>
                                            <div className="s-eye sr" style={{"justifyContent":"center"}}><div className="s-el"></div></div>
                                            <div className="sb sr" style={{"display":"inline-flex"}}>🖼 Project Preview</div>
                                            <h2 className="st sr" style={{"textAlign":"center"}}>See DevTrack AI<br /><span style={{"color":"var(--t)"}}>in action</span></h2>
                                            <p style={{"fontSize":"15px","color":"var(--g500)","textAlign":"center","margin":"8px auto 0","maxWidth":"420px"}} className="sr">Browse every module. Drop your own screenshots to customize.</p>
                                        </div>
                                        <div className="gallery-stage" id="gStage">
                                            <div style={{"position":"absolute","inset":"0","display":"flex","alignItems":"center","justifyContent":"center"}}>
                                                {/*  SLIDE 0  */}
                                                <div className="gi" data-gi="0">
                                                    <div className="gi-bar"><div className="gi-tls"><div className="gi-tl gi-tlr"></div><div className="gi-tl gi-tly"></div><div className="gi-tl gi-tlg"></div></div><div className="gi-url">devtrack.ai / dashboard</div><div className="gi-bdg">Dashboard</div></div>
                                                    <div className="gi-content">
                                                        <div style={{"display":"grid","gridTemplateColumns":"repeat(4,1fr)","gap":"10px","marginBottom":"16px"}}>
                                                            <div style={{"background":"linear-gradient(135deg,var(--t),var(--td))","borderRadius":"12px","padding":"14px","textAlign":"center"}}><div style={{"fontSize":"26px","fontWeight":"900","color":"#fff"}}>87</div><div style={{"fontSize":"9px","color":"rgba(255,255,255,.7)","marginTop":"2px","fontWeight":"600"}}>HEALTH</div></div>
                                                            <div style={{"background":"var(--g50)","borderRadius":"12px","padding":"14px","textAlign":"center","border":"1px solid var(--g100)"}}><div style={{"fontSize":"26px","fontWeight":"900","color":"var(--g900)"}}>24</div><div style={{"fontSize":"9px","color":"var(--g400)","marginTop":"2px","fontWeight":"600"}}>REQS</div></div>
                                                            <div style={{"background":"rgba(34,197,94,.06)","borderRadius":"12px","padding":"14px","textAlign":"center","border":"1px solid rgba(34,197,94,.15)"}}><div style={{"fontSize":"26px","fontWeight":"900","color":"var(--green)"}}>92%</div><div style={{"fontSize":"9px","color":"var(--g400)","marginTop":"2px","fontWeight":"600"}}>TESTS</div></div>
                                                            <div style={{"background":"rgba(139,92,246,.06)","borderRadius":"12px","padding":"14px","textAlign":"center","border":"1px solid rgba(139,92,246,.15)"}}><div style={{"fontSize":"26px","fontWeight":"900","color":"var(--purple)"}}>78%</div><div style={{"fontSize":"9px","color":"var(--g400)","marginTop":"2px","fontWeight":"600"}}>EVIDENCE</div></div>
                                                        </div>
                                                        <div style={{"display":"grid","gridTemplateColumns":"3fr 2fr","gap":"12px","marginBottom":"14px"}}>
                                                            <div style={{"background":"var(--g50)","borderRadius":"12px","padding":"14px","border":"1px solid var(--g100)"}}><div style={{"fontSize":"11px","fontWeight":"700","color":"var(--g700)","marginBottom":"9px"}}>Sprint Velocity</div><div style={{"display":"flex","alignItems":"flex-end","gap":"5px","height":"56px"}}><div style={{"flex":"1","display":"flex","gap":"2px","alignItems":"flex-end","height":"100%"}}><div style={{"flex":"1","background":"var(--t)","borderRadius":"2px 2px 0 0","height":"55%"}}></div><div style={{"flex":"1","background":"var(--g200)","borderRadius":"2px 2px 0 0","height":"75%"}}></div></div><div style={{"flex":"1","display":"flex","gap":"2px","alignItems":"flex-end","height":"100%"}}><div style={{"flex":"1","background":"var(--t)","borderRadius":"2px 2px 0 0","height":"70%"}}></div><div style={{"flex":"1","background":"var(--g200)","borderRadius":"2px 2px 0 0","height":"80%"}}></div></div><div style={{"flex":"1","display":"flex","gap":"2px","alignItems":"flex-end","height":"100%"}}><div style={{"flex":"1","background":"var(--t)","borderRadius":"2px 2px 0 0","height":"85%"}}></div><div style={{"flex":"1","background":"var(--g200)","borderRadius":"2px 2px 0 0","height":"85%"}}></div></div><div style={{"flex":"1","display":"flex","gap":"2px","alignItems":"flex-end","height":"100%"}}><div style={{"flex":"1","background":"var(--t)","borderRadius":"2px 2px 0 0","height":"78%"}}></div><div style={{"flex":"1","background":"var(--g200)","borderRadius":"2px 2px 0 0","height":"90%"}}></div></div></div></div>
                                                            <div style={{"background":"rgba(30,112,125,.05)","border":"1px solid rgba(30,112,125,.12)","borderRadius":"12px","padding":"14px"}}><div style={{"fontSize":"10px","fontWeight":"700","color":"var(--t)","marginBottom":"7px"}}>✦ AI Insights</div><div style={{"fontSize":"10px","color":"var(--g600)","lineHeight":"1.7"}}>• Velocity 23% below<br />• 3 reqs missing tests<br />• 5 tasks no evidence</div></div>
                                                        </div>
                                                        <div style={{"background":"linear-gradient(135deg,rgba(30,112,125,.05),rgba(34,197,212,.03))","border":"1.5px dashed rgba(30,112,125,.2)","borderRadius":"12px","padding":"20px","textAlign":"center","display":"flex","flexDirection":"column","alignItems":"center","gap":"6px","cursor":"pointer"}}><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--t)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg><div style={{"fontSize":"12px","color":"var(--g500)","fontWeight":"500"}}>Drop your Dashboard screenshot here</div></div>
                                                    </div>
                                                    <div className="gi-info"><div className="gi-num">01</div><div className="gi-title">Project Dashboard</div></div>
                                                </div>
                                                {/*  SLIDE 1  */}
                                                <div className="gi" data-gi="1">
                                                    <div className="gi-bar"><div className="gi-tls"><div className="gi-tl gi-tlr"></div><div className="gi-tl gi-tly"></div><div className="gi-tl gi-tlg"></div></div><div className="gi-url">devtrack.ai / kanban</div><div className="gi-bdg" style={{"background":"rgba(139,92,246,.1)","color":"var(--purple)"}}>Kanban</div></div>
                                                    <div className="gi-content" style={{"padding":"16px 20px 68px"}}>
                                                        <div style={{"display":"grid","gridTemplateColumns":"repeat(4,1fr)","gap":"8px"}}>
                                                            <div style={{"background":"var(--g50)","borderRadius":"10px","padding":"10px","border":"1px solid var(--g100)"}}><div style={{"fontSize":"9px","fontWeight":"700","color":"var(--g400)","textTransform":"uppercase","marginBottom":"8px"}}>TO DO · 7</div><div style={{"background":"#fff","borderRadius":"6px","padding":"8px","border":"1px solid var(--g200)","fontSize":"10px","color":"var(--g700)","marginBottom":"5px"}}>Payment gateway<span style={{"display":"block","marginTop":"3px","fontSize":"8px","background":"rgba(30,112,125,.1)","color":"var(--t)","padding":"1px 5px","borderRadius":"3px","fontWeight":"700","width":"fit-content"}}>Backend</span></div><div style={{"background":"#fff","borderRadius":"6px","padding":"8px","border":"1px solid var(--g200)","fontSize":"10px","color":"var(--g700)"}}>Cart UI<span style={{"display":"block","marginTop":"3px","fontSize":"8px","background":"rgba(139,92,246,.1)","color":"var(--purple)","padding":"1px 5px","borderRadius":"3px","fontWeight":"700","width":"fit-content"}}>Frontend</span></div></div>
                                                            <div style={{"background":"var(--g50)","borderRadius":"10px","padding":"10px","border":"1px solid var(--g100)"}}><div style={{"fontSize":"9px","fontWeight":"700","color":"var(--t)","textTransform":"uppercase","marginBottom":"8px"}}>IN PROG · 5</div><div style={{"background":"#fff","borderRadius":"6px","padding":"8px","border":"1px solid var(--g200)","borderLeft":"2px solid var(--t)","fontSize":"10px","color":"var(--g700)","marginBottom":"5px"}}>Auth JWT<span style={{"display":"block","marginTop":"3px","fontSize":"8px","background":"rgba(30,112,125,.1)","color":"var(--t)","padding":"1px 5px","borderRadius":"3px","fontWeight":"700","width":"fit-content"}}>Backend</span></div><div style={{"background":"#fff","borderRadius":"6px","padding":"8px","border":"1px solid var(--g200)","borderLeft":"2px solid var(--purple)","fontSize":"10px","color":"var(--g700)"}}>Product list<span style={{"display":"block","marginTop":"3px","fontSize":"8px","background":"rgba(139,92,246,.1)","color":"var(--purple)","padding":"1px 5px","borderRadius":"3px","fontWeight":"700","width":"fit-content"}}>Frontend</span></div></div>
                                                            <div style={{"background":"var(--g50)","borderRadius":"10px","padding":"10px","border":"1px solid var(--g100)"}}><div style={{"fontSize":"9px","fontWeight":"700","color":"var(--amber)","textTransform":"uppercase","marginBottom":"8px"}}>REVIEW · 3</div><div style={{"background":"#fff","borderRadius":"6px","padding":"8px","border":"1px solid var(--g200)","borderLeft":"2px solid var(--amber)","fontSize":"10px","color":"var(--g700)"}}>User register<span style={{"display":"block","marginTop":"3px","fontSize":"8px","background":"rgba(34,197,94,.1)","color":"var(--green)","padding":"1px 5px","borderRadius":"3px","fontWeight":"700","width":"fit-content"}}>PR #12 ✓</span></div></div>
                                                            <div style={{"background":"var(--g50)","borderRadius":"10px","padding":"10px","border":"1px solid var(--g100)"}}><div style={{"fontSize":"9px","fontWeight":"700","color":"var(--green)","textTransform":"uppercase","marginBottom":"8px"}}>DONE · 16</div><div style={{"background":"#fff","borderRadius":"6px","padding":"8px","border":"1px solid var(--g200)","opacity":".7","fontSize":"10px","color":"var(--g700)","marginBottom":"5px"}}>CI/CD setup<span style={{"display":"block","marginTop":"3px","fontSize":"8px","background":"rgba(34,197,94,.1)","color":"var(--green)","padding":"1px 5px","borderRadius":"3px","fontWeight":"700","width":"fit-content"}}>Done ✓</span></div><div style={{"background":"#fff","borderRadius":"6px","padding":"8px","border":"1px solid var(--g200)","opacity":".7","fontSize":"10px","color":"var(--g700)"}}>UML approved<span style={{"display":"block","marginTop":"3px","fontSize":"8px","background":"rgba(34,197,94,.1)","color":"var(--green)","padding":"1px 5px","borderRadius":"3px","fontWeight":"700","width":"fit-content"}}>Done ✓</span></div></div>
                                                        </div>
                                                        <div style={{"marginTop":"12px","background":"linear-gradient(135deg,rgba(139,92,246,.05),rgba(99,102,241,.03))","border":"1.5px dashed rgba(139,92,246,.2)","borderRadius":"12px","padding":"16px","textAlign":"center","display":"flex","flexDirection":"column","alignItems":"center","gap":"5px","cursor":"pointer"}}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--purple)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="5" height="18" rx="1"/><rect x="10" y="3" width="5" height="12" rx="1"/><rect x="17" y="3" width="5" height="8" rx="1"/></svg><div style={{"fontSize":"11px","color":"var(--g500)","fontWeight":"500"}}>Drop your Kanban screenshot here</div></div>
                                                    </div>
                                                    <div className="gi-info"><div className="gi-num">02</div><div className="gi-title">Kanban Board</div></div>
                                                </div>
                                                {/*  SLIDE 2: Traceability dark  */}
                                                <div className="gi" data-gi="2" style={{"background":"var(--g900)"}}>
                                                    <div className="gi-bar" style={{"background":"rgba(255,255,255,.04)","borderColor":"rgba(255,255,255,.07)"}}><div className="gi-tls"><div className="gi-tl gi-tlr"></div><div className="gi-tl gi-tly"></div><div className="gi-tl gi-tlg"></div></div><div className="gi-url" style={{"background":"rgba(255,255,255,.06)","borderColor":"rgba(255,255,255,.1)","color":"rgba(255,255,255,.4)"}}>devtrack.ai / traceability</div><div className="gi-bdg" style={{"background":"rgba(30,112,125,.25)","color":"var(--cl)"}}>Traceability</div></div>
                                                    <div className="gi-content">
                                                        <div style={{"display":"flex","flexDirection":"column","gap":"3px"}}>
                                                            <div style={{"display":"flex","alignItems":"center","gap":"9px","padding":"9px 12px","background":"rgba(30,112,125,.18)","borderRadius":"9px","border":"1px solid rgba(30,112,125,.3)"}}><div style={{"width":"22px","height":"22px","borderRadius":"6px","background":"rgba(30,112,125,.4)","display":"flex","alignItems":"center","justifyContent":"center","flexShrink":"0"}}><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="var(--cl)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/></svg></div><span style={{"fontSize":"11px","fontWeight":"600","color":"#fff"}}>REQ-001 — User Authentication</span><span style={{"marginLeft":"auto","fontSize":"8px","background":"rgba(99,102,241,.25)","color":"#a5b4fc","padding":"2px 6px","borderRadius":"100px","fontWeight":"700"}}>Functional</span></div>
                                                            <div style={{"marginLeft":"14px","paddingLeft":"12px","borderLeft":"1.5px dashed rgba(255,255,255,.1)"}}>
                                                                <div style={{"display":"flex","alignItems":"center","gap":"9px","padding":"8px 12px","background":"rgba(99,102,241,.12)","borderRadius":"8px","border":"1px solid rgba(99,102,241,.2)","marginBottom":"3px"}}><div style={{"width":"20px","height":"20px","borderRadius":"5px","background":"rgba(99,102,241,.3)","display":"flex","alignItems":"center","justifyContent":"center","flexShrink":"0"}}><svg width="9" height="9" viewBox="0 0 24 24" fill="none" stroke="#a5b4fc" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg></div><span style={{"fontSize":"10px","fontWeight":"600","color":"rgba(255,255,255,.8)"}}>UC-002 — Login Flow</span><span style={{"marginLeft":"auto","fontSize":"8px","background":"rgba(34,197,94,.15)","color":"var(--green)","padding":"2px 6px","borderRadius":"100px","fontWeight":"700"}}>Approved</span></div>
                                                                <div style={{"marginLeft":"14px","paddingLeft":"12px","borderLeft":"1.5px dashed rgba(255,255,255,.07)"}}>
                                                                    <div style={{"display":"flex","alignItems":"center","gap":"9px","padding":"8px 12px","background":"rgba(34,197,94,.08)","borderRadius":"8px","border":"1px solid rgba(34,197,94,.15)","marginBottom":"3px"}}><div style={{"width":"20px","height":"20px","borderRadius":"5px","background":"rgba(34,197,94,.25)","display":"flex","alignItems":"center","justifyContent":"center","flexShrink":"0"}}><svg width="9" height="9" viewBox="0 0 24 24" fill="none" stroke="var(--green)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg></div><span style={{"fontSize":"10px","fontWeight":"600","color":"rgba(255,255,255,.75)"}}>TASK-014 — JWT Auth</span><span style={{"marginLeft":"auto","fontSize":"8px","background":"rgba(34,197,94,.15)","color":"var(--green)","padding":"2px 6px","borderRadius":"100px","fontWeight":"700"}}>Done</span></div>
                                                                    <div style={{"marginLeft":"14px","paddingLeft":"12px","borderLeft":"1.5px dashed rgba(255,255,255,.05)"}}>
                                                                        <div style={{"display":"flex","alignItems":"center","gap":"9px","padding":"8px 12px","background":"rgba(245,158,11,.07)","borderRadius":"8px","border":"1px solid rgba(245,158,11,.15)","marginBottom":"3px"}}><div style={{"width":"20px","height":"20px","borderRadius":"5px","background":"rgba(245,158,11,.25)","display":"flex","alignItems":"center","justifyContent":"center","flexShrink":"0"}}><svg width="9" height="9" viewBox="0 0 24 24" fill="none" stroke="var(--amber)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M9 3h6m-5 0v7l-5 8a1 1 0 0 0 .9 1.5h12.2A1 1 0 0 0 19 18l-5-8V3"/></svg></div><span style={{"fontSize":"10px","fontWeight":"600","color":"rgba(255,255,255,.7)"}}>TEST-007 — Auth Suite</span><span style={{"marginLeft":"auto","fontSize":"8px","background":"rgba(34,197,94,.15)","color":"var(--green)","padding":"2px 6px","borderRadius":"100px","fontWeight":"700"}}>Pass</span></div>
                                                                        <div style={{"marginLeft":"14px","paddingLeft":"12px","borderLeft":"1.5px dashed rgba(255,255,255,.04)"}}><div style={{"display":"flex","alignItems":"center","gap":"9px","padding":"8px 12px","background":"rgba(139,92,246,.08)","borderRadius":"8px","border":"1px solid rgba(139,92,246,.15)"}}><div style={{"width":"20px","height":"20px","borderRadius":"5px","background":"rgba(139,92,246,.25)","display":"flex","alignItems":"center","justifyContent":"center","flexShrink":"0"}}><svg width="9" height="9" viewBox="0 0 24 24" fill="none" stroke="#c4b5fd" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21.44 11.05l-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48"/></svg></div><span style={{"fontSize":"10px","fontWeight":"600","color":"rgba(255,255,255,.65)"}}>PR #12, screenshot.png</span><span style={{"marginLeft":"auto","fontSize":"8px","background":"rgba(34,197,94,.15)","color":"var(--green)","padding":"2px 6px","borderRadius":"100px","fontWeight":"700"}}>Valid</span></div></div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div style={{"background":"linear-gradient(135deg,rgba(30,112,125,.1),rgba(34,197,212,.05))","border":"1.5px dashed rgba(30,112,125,.3)","borderRadius":"12px","padding":"16px","textAlign":"center","display":"flex","flexDirection":"column","alignItems":"center","gap":"5px","marginTop":"12px","cursor":"pointer"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--cl)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg><div style={{"fontSize":"11px","color":"rgba(255,255,255,.35)","fontWeight":"500"}}>Drop Traceability screenshot here</div></div>
                                                    </div>
                                                    <div className="gi-info" style={{"background":"linear-gradient(0deg,rgba(15,28,30,.98) 60%,transparent)"}}><div className="gi-num" style={{"color":"var(--cl)"}}>03</div><div className="gi-title" style={{"color":"#fff"}}>Traceability Tree</div></div>
                                                </div>
                                                {/*  SLIDE 3: Code Insight dark  */}
                                                <div className="gi" data-gi="3" style={{"background":"var(--g800)"}}>
                                                    <div className="gi-bar" style={{"background":"rgba(255,255,255,.04)","borderColor":"rgba(255,255,255,.07)"}}><div className="gi-tls"><div className="gi-tl gi-tlr"></div><div className="gi-tl gi-tly"></div><div className="gi-tl gi-tlg"></div></div><div className="gi-url" style={{"background":"rgba(255,255,255,.06)","borderColor":"rgba(255,255,255,.1)","color":"rgba(255,255,255,.4)"}}>devtrack.ai / code-insight</div><div className="gi-bdg" style={{"background":"linear-gradient(135deg,var(--t),var(--c))","color":"#fff"}}>Code Insight</div></div>
                                                    <div className="gi-content">
                                                        <div style={{"background":"rgba(255,255,255,.04)","border":"1px solid rgba(255,255,255,.08)","borderRadius":"12px","padding":"13px","marginBottom":"9px"}}><div style={{"display":"flex","alignItems":"center","justifyContent":"space-between","marginBottom":"8px"}}><div><div style={{"fontSize":"11px","fontWeight":"700","color":"#fff"}}>PR #12 — feat/user-auth</div><div style={{"fontSize":"9px","color":"rgba(255,255,255,.35)","marginTop":"2px"}}>by @nam-tran · 14 files</div></div><div style={{"textAlign":"right"}}><div style={{"fontSize":"22px","fontWeight":"900","color":"var(--green)"}}>94</div><div style={{"fontSize":"8px","color":"rgba(255,255,255,.35)"}}>/100</div></div></div><div style={{"height":"4px","background":"rgba(255,255,255,.1)","borderRadius":"100px","overflow":"hidden","marginBottom":"7px"}}><div style={{"width":"94%","height":"100%","background":"linear-gradient(90deg,var(--green),#16a34a)","borderRadius":"100px"}}></div></div><div style={{"display":"flex","gap":"5px","marginBottom":"8px"}}><span style={{"fontSize":"8px","fontWeight":"700","padding":"2px 7px","borderRadius":"100px","background":"rgba(34,197,94,.15)","color":"var(--green)"}}>✓ CI Passed</span><span style={{"fontSize":"8px","fontWeight":"700","padding":"2px 7px","borderRadius":"100px","background":"rgba(34,197,212,.15)","color":"var(--cl)"}}>✓ Clean Code</span></div><div style={{"display":"flex","gap":"7px"}}><div style={{"flex":"1","padding":"9px","borderRadius":"8px","background":"linear-gradient(135deg,var(--green),#16a34a)","color":"#fff","fontSize":"11px","fontWeight":"700","textAlign":"center","cursor":"pointer"}}>✓ Approve</div><div style={{"flex":"1","padding":"9px","borderRadius":"8px","background":"rgba(239,68,68,.12)","border":"1px solid rgba(239,68,68,.25)","color":"var(--red)","fontSize":"11px","fontWeight":"700","textAlign":"center","cursor":"pointer"}}>✗ Reject</div></div></div>
                                                        <div style={{"background":"rgba(239,68,68,.06)","border":"1px solid rgba(239,68,68,.2)","borderRadius":"12px","padding":"13px","marginBottom":"9px"}}><div style={{"display":"flex","alignItems":"center","justifyContent":"space-between","marginBottom":"8px"}}><div><div style={{"fontSize":"11px","fontWeight":"700","color":"#ff8a8a"}}>PR #14 — feat/payment</div><div style={{"fontSize":"9px","color":"rgba(255,255,255,.35)","marginTop":"2px"}}>by @thien-le · 8 files</div></div><div style={{"textAlign":"right"}}><div style={{"fontSize":"22px","fontWeight":"900","color":"var(--red)"}}>52</div><div style={{"fontSize":"8px","color":"rgba(255,255,255,.35)"}}>/100</div></div></div><div style={{"height":"4px","background":"rgba(255,255,255,.1)","borderRadius":"100px","overflow":"hidden","marginBottom":"7px"}}><div style={{"width":"52%","height":"100%","background":"linear-gradient(90deg,var(--red),#dc2626)","borderRadius":"100px"}}></div></div><div style={{"display":"flex","gap":"5px"}}><span style={{"fontSize":"8px","fontWeight":"700","padding":"2px 7px","borderRadius":"100px","background":"rgba(239,68,68,.15)","color":"var(--red)"}}>✗ CI Failed</span><span style={{"fontSize":"8px","fontWeight":"700","padding":"2px 7px","borderRadius":"100px","background":"rgba(245,158,11,.15)","color":"var(--amber)"}}>⚠ No Tests</span><span style={{"fontSize":"8px","fontWeight":"700","padding":"2px 7px","borderRadius":"100px","background":"rgba(239,68,68,.15)","color":"var(--red)"}}>✗ Key Leak</span></div></div>
                                                        <div style={{"background":"linear-gradient(135deg,rgba(30,112,125,.1),rgba(34,197,212,.05))","border":"1.5px dashed rgba(30,112,125,.3)","borderRadius":"12px","padding":"14px","textAlign":"center","display":"flex","flexDirection":"column","alignItems":"center","gap":"5px","cursor":"pointer"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--cl)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg><div style={{"fontSize":"11px","color":"rgba(255,255,255,.35)","fontWeight":"500"}}>Drop Code Insight screenshot here</div></div>
                                                    </div>
                                                    <div className="gi-info" style={{"background":"linear-gradient(0deg,rgba(26,46,49,.98) 60%,transparent)"}}><div className="gi-num" style={{"color":"var(--cl)"}}>04</div><div className="gi-title" style={{"color":"#fff"}}>Code Insight</div></div>
                                                </div>
                                                {/*  SLIDE 4  */}
                                                <div className="gi" data-gi="4">
                                                    <div className="gi-bar"><div className="gi-tls"><div className="gi-tl gi-tlr"></div><div className="gi-tl gi-tly"></div><div className="gi-tl gi-tlg"></div></div><div className="gi-url">devtrack.ai / ...</div><div className="gi-bdg">Your Screen</div></div>
                                                    <div className="gi-content" style={{"display":"flex","flexDirection":"column","alignItems":"center","justifyContent":"center","minHeight":"380px","gap":"16px"}}>
                                                        <div style={{"width":"80px","height":"80px","borderRadius":"20px","background":"linear-gradient(135deg,rgba(30,112,125,.1),rgba(34,197,212,.06))","border":"2px dashed rgba(30,112,125,.3)","display":"flex","alignItems":"center","justifyContent":"center"}}><svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="var(--t)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg></div>
                                                        <div style={{"fontSize":"20px","fontWeight":"800","color":"var(--g800)","letterSpacing":"-.5px"}}>Add Your Screenshots</div>
                                                        <div style={{"fontSize":"13px","color":"var(--g500)","textAlign":"center","maxWidth":"300px","lineHeight":"1.7"}}>Requirements, UML editor, Evidence upload, Mentor dashboard — any module of DevTrack AI</div>
                                                        <div style={{"display":"flex","gap":"10px"}}><div style={{"padding":"10px 20px","background":"var(--t)","color":"#fff","borderRadius":"9px","fontSize":"12px","fontWeight":"700","cursor":"pointer"}}>+ Upload Image</div><div style={{"padding":"10px 20px","background":"#fff","border":"1.5px solid var(--g200)","color":"var(--g700)","borderRadius":"9px","fontSize":"12px","fontWeight":"600","cursor":"pointer"}}>Use URL</div></div>
                                                    </div>
                                                    <div className="gi-info"><div className="gi-num">05</div><div className="gi-title">Your Project Screenshots</div></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="gal-nav">
                                            <button className="gnbtn" id="gPrev">←</button>
                                            <div style={{"display":"flex","gap":"7px","alignItems":"center"}} id="gDots"><div className="gd2 a" data-gi="0"></div><div className="gd2" data-gi="1"></div><div className="gd2" data-gi="2"></div><div className="gd2" data-gi="3"></div><div className="gd2" data-gi="4"></div></div>
                                            <button className="gnbtn" id="gNext">→</button>
                                        </div>
                                    </section>
    </>
  );
};

export default LandingGallery;
