const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const { promisify } = require('util');

const execAsync = promisify(exec);

// ─── Script Sanitizer ────────────────────────────────────────
// Scripts generated by templateEngine.js (cloud) contain WebSocket + CDP
// Screencast code that only works inside the Docker playwright-service.
// Local agent doesn't need live streaming — strip it all out.
//
// Strategy: remove ENTIRE CONTIGUOUS BLOCKS, not individual lines.
// Line-by-line removal leaves orphan code (resolve, });, setTimeout)
// which causes syntax errors → Playwright can't parse → suites:[].
function sanitizeScript(script) {
    // Không còn sanitize cắt bỏ đoạn WebSocket nữa,
    // script sẽ giữ nguyên kết nối WS để truyền CDP frames
    return script;
}

async function executeScript(script, baseRunId, baseUrl, envOverrides = {}) {
    const uniqueRunId = `${baseRunId}-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
    const tempDir = path.join(__dirname, 'temp', uniqueRunId);
    const scriptPath = path.join(tempDir, 'test.spec.js');
    const screenshotDir = path.join(tempDir, 'screenshots');

    fs.mkdirSync(screenshotDir, { recursive: true });

    // Strip WebSocket/CDP code that only works in the cloud playwright-service
    const cleanScript = sanitizeScript(script);

    const scriptWithAbsPath = cleanScript.replace(
        /path:\s*['"]([^'"]+\.png)['"]/g,
        (_, filename) => {
            const absPath = path.join(screenshotDir, filename).replace(/\\/g, '/');
            return `path: '${absPath}'`;
        }
    );

    fs.writeFileSync(scriptPath, scriptWithAbsPath, 'utf8');
    console.log('[Executor] Script sanitized and written to:', scriptPath);
    console.log('[Executor] Sanitized script preview (first 500 chars):\n', scriptWithAbsPath.substring(0, 500));

    const startTime = Date.now();
    let result;

    try {
        const safeScriptPath = scriptPath.replace(/\\/g, '/');
        const liveStatusFile = path.join(tempDir, 'live_status.json');
        const reporterPath = path.join(__dirname, 'reporter.js').replace(/\\/g, '/');
        const ext = process.platform === 'win32' ? '.cmd' : '';
        const playwrightBin = path.join(__dirname, 'node_modules', '.bin', `playwright${ext}`).replace(/\\/g, '/');

        console.log('[Executor] Running:', `"${playwrightBin}" test "${safeScriptPath}" --reporter=json --timeout=120000 --workers=1`);

        const { stdout, stderr } = await execAsync(
            `"${playwrightBin}" test "${safeScriptPath}" --reporter=json --timeout=120000 --workers=1`,
            {
                cwd: __dirname,
                timeout: 180000,
                env: { 
                    ...process.env, 
                    BASE_URL: baseUrl, 
                    LIVE_STATUS_FILE: liveStatusFile,
                    WS_URL: envOverrides.WS_URL || 'ws://localhost:4001'
                },
                maxBuffer: 10 * 1024 * 1024,
            }
        );
        if (stderr) {
            console.error('[Executor] stderr (success path):', stderr.substring(0, 1000));
        }
        console.log('[Executor] stdout length:', stdout.length);
        result = parseOutput(stdout, screenshotDir);
    } catch (err) {
        // Playwright exits with non-zero when tests fail — that's normal.
        // We still get stdout with the JSON report.
        console.error('[Executor] Playwright exited with error. Code:', err.code);
        if (err.stderr) {
            console.error('[Executor] stderr:', err.stderr.substring(0, 1000));
        }
        if (err.stdout) {
            console.log('[Executor] stdout length:', err.stdout.length);
            console.log('[Executor] stdout preview:', err.stdout.substring(0, 300));
            result = parseOutput(err.stdout, screenshotDir);
        } else {
            console.error('[Executor] No stdout from Playwright! Error:', err.message);
            result = {
                status: 'ERROR',
                error: { message: err.message, type: 'EXECUTION_ERROR' },
                steps: [],
                screenshots: [],
            };
        }
    }

    result.duration = Date.now() - startTime;
    result.screenshots = [];

    cleanupTempDir(tempDir);
    return result;
}

function parseOutput(stdout, screenshotDir) {
    let report;
    try {
        // Playwright JSON reporter may output non-JSON lines before/after.
        // Find the outermost JSON object.
        const jsonStart = stdout.indexOf('{');
        const jsonEnd = stdout.lastIndexOf('}');
        if (jsonStart === -1 || jsonEnd === -1) {
            throw new Error('No JSON found in output');
        }
        const jsonStr = stdout.substring(jsonStart, jsonEnd + 1);
        report = JSON.parse(jsonStr);
    } catch (parseErr) {
        console.error('[Executor] JSON parse failed:', parseErr.message);
        console.error('[Executor] Raw stdout (first 500 chars):', (stdout || '').substring(0, 500));
        return {
            status: 'ERROR',
            error: { message: 'Không parse được output từ Playwright', raw: (stdout || '').substring(0, 1000) },
            steps: [],
            screenshots: [],
        };
    }

    // ── Robust test result extraction ──
    // Playwright JSON structure varies by version. Try multiple paths:
    //   report.suites[0].specs[0].tests[0]           — flat structure (v1.40+)
    //   report.suites[0].suites[0].specs[0].tests[0] — nested structure (v1.50+)
    //   Walk all suites recursively as a fallback
    let testResult = null;

    function findFirstTest(suites) {
        if (!suites) return null;
        for (const suite of suites) {
            // Check specs at this level
            if (suite.specs) {
                for (const spec of suite.specs) {
                    if (spec.tests && spec.tests.length > 0) {
                        return spec.tests[0];
                    }
                }
            }
            // Recurse into nested suites
            if (suite.suites) {
                const found = findFirstTest(suite.suites);
                if (found) return found;
            }
        }
        return null;
    }

    testResult = findFirstTest(report.suites);

    if (!testResult) {
        console.error('[Executor] No test result found in JSON report. Suites:', JSON.stringify(report.suites, null, 2).substring(0, 500));
        return {
            status: 'ERROR',
            error: { message: 'Không tìm thấy kết quả test trong JSON report' },
            steps: [],
            screenshots: [],
        };
    }

    const passed = testResult.status === 'expected' || testResult.status === 'passed';

    let flatSteps = [];
    function extractTestSteps(node) {
        if (!node) return;
        if (node.category === 'test.step') {
            flatSteps.push({
                title: node.title,
                duration: node.duration,
                status: node.error ? 'FAIL' : 'PASS',
                error: node.error?.message ? node.error.message.replace(/\x1b\[[0-9;]*m/g, '') : null,
            });
        }
        if (node.steps && Array.isArray(node.steps)) {
            for (const child of node.steps) {
                extractTestSteps(child);
            }
        }
    }

    if (testResult.results?.[0]?.steps) {
        for (const s of testResult.results[0].steps) {
            extractTestSteps(s);
        }
    }

    const steps = flatSteps;

    const rawError = testResult.results?.[0]?.error;
    const failedStepIndex = steps.findIndex(s => s.status === 'FAIL');

    const error = passed
        ? null
        : {
            message: (rawError?.message || 'Test thất bại').replace(/\x1b\[[0-9;]*m/g, ''),
            stack: (rawError?.stack || '').replace(/\x1b\[[0-9;]*m/g, ''),
            failedStep: steps.find(s => s.status === 'FAIL')?.title || null,
            failedStepIndex: failedStepIndex >= 0 ? failedStepIndex : null
        };

    return { status: passed ? 'PASS' : 'FAIL', steps, screenshots: [], error };
}

function cleanupTempDir(tempDir) {
    try {
        fs.rmSync(tempDir, { recursive: true, force: true });
    } catch (e) { }
}

async function executeApiTest(script) {
    const startTime = Date.now();
    try {
        const config = JSON.parse(script);
        const url = config.url;
        const method = config.method || 'GET';
        const headers = config.headers || {};
        let body = config.body || null;

        const options = { method, headers };
        if (body && ['POST', 'PUT', 'PATCH'].includes(method.toUpperCase())) {
            options.body = typeof body === 'object' ? JSON.stringify(body) : String(body);
        }

        const res = await fetch(url, options);
        const timeMs = Date.now() - startTime;
        
        const responseBody = await res.text();
        const responseHeaders = {};
        res.headers.forEach((value, key) => {
            responseHeaders[key] = value;
        });

        return {
            status: 'PASS',
            duration: timeMs,
            apiResult: {
                status: res.status,
                timeMs: timeMs,
                body: responseBody,
                headers: responseHeaders
            }
        };
    } catch (err) {
        return {
            status: 'ERROR',
            duration: Date.now() - startTime,
            apiResult: {
                error: err.message
            }
        };
    }
}

module.exports = { executeScript, executeApiTest };
