export { default as IssueTrackerDashboard } from './pages/IssueTrackerDashboard'
export { default as IssueDetailView } from './pages/IssueDetailView'
export { default as BugsPage } from './pages/BugsPage'
export { default as BugDetailPage } from './pages/BugDetailPage'
export { ProjectGithubConfig } from './pages/ProjectGithubConfig'
export { GitHubCallbackPage } from './pages/GitHubCallbackPage'
export { default as FeatureDiscussionPage } from './pages/FeatureDiscussionPage'
export { default as CreateBugModal } from './components/CreateBugModal'
export { default as bugService } from './services/bugService'
