import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import useProjectStore from '../../../store/useProjectStore';
import { requirementApi } from '../services/requirementApi';
import toast from 'react-hot-toast';
import AiSmartSyncAllModal from './AiSmartSyncAllModal';
import Button from '../../../components/ui/Button';

const RequirementDetailHeader = ({ requirement, onEdit, onRefresh }) => {
  const { projectId } = useParams();
  const [isSmartSyncModalOpen, setIsSmartSyncModalOpen] = useState(false);

  if (!requirement) return null;

  const handleApprove = async () => {
    try {
      await requirementApi.updateStatus(requirement.id, 'DONE');
      if (onRefresh) onRefresh();
    } catch (error) {
      console.error('Lỗi khi duyệt Requirement:', error);
    }
  };

  const handleAiModalSuccess = () => {
    if (onRefresh) onRefresh();
  };

  const hasExistingUseCases = requirement.useCases && requirement.useCases.length > 0;
  const hasOutdatedUseCases = requirement.useCases?.some(uc => uc.outdated);

  // Determine button styles and text based on context
  let btnVariant = 'primary';
  let btnText = '🪄 Generate Use Cases';
  let extraProps = {};
  
  if (hasExistingUseCases) {
    btnText = '🪄 AI Update Usecase';
    if (hasOutdatedUseCases) {
      btnVariant = 'danger'; // Use danger or custom for pulse
      extraProps = { className: 'animate-pulse-slow shadow-amber-500/30' };
    }
  }

  return (
    <div className="flex flex-col md:flex-row md:items-start justify-between mb-gutter gap-stack_md pb-4 border-b border-outline-variant/50">
      <div className="flex-1">
        {/* Breadcrumb & Badges */}
        <div className="flex items-center gap-3 mb-3">
          <Link to={`/projects/${projectId}/requirements`} className="flex items-center gap-1 text-secondary hover:text-[#1E707D] transition-colors font-body-md text-body-md">
            <span className="material-symbols-outlined text-[18px]">arrow_back</span>
            Requirements
          </Link>
          <div className="w-px h-4 bg-outline-variant"></div>
          <span className="font-label-md text-label-md bg-[#1E707D]/10 text-[#1E707D] px-2 py-1 rounded font-bold">
            {requirement.reqCode || `REQ-${String(requirement.id).padStart(2, '0')}`}
          </span>
          {requirement.status && (
            <span className={`inline-flex items-center justify-center px-2 py-0.5 rounded text-[10px] font-bold tracking-wider uppercase border ${
              requirement.status === 'DRAFT'        ? 'bg-slate-50 text-slate-600 border-slate-200' :
              requirement.status === 'IN_PROGRESS'  ? 'bg-amber-50 text-amber-700 border-amber-200' :
              requirement.status === 'IN_REVIEW'    ? 'bg-[#1E707D]/10 text-[#1E707D] border-[#1E707D]/20' :
              requirement.status === 'DONE'         ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :
              'bg-surface-container text-secondary border-outline-variant'
            }`}>
              {requirement.status.replace('_', ' ')}
            </span>
          )}
          {requirement.priority && (
            <span className={`inline-flex items-center justify-center px-2 py-0.5 rounded text-[10px] font-bold tracking-wider uppercase border ${
              requirement.priority === 'CRITICAL' ? 'bg-red-50 text-red-700 border-red-200' :
              requirement.priority === 'HIGH' ? 'bg-orange-50 text-orange-700 border-orange-200' :
              requirement.priority === 'MEDIUM' ? 'bg-[#1E707D]/10 text-[#1E707D] border-[#1E707D]/20' :
              requirement.priority === 'LOW' ? 'bg-slate-50 text-slate-700 border-slate-200' :
              'bg-surface-container text-secondary border-outline-variant'
            }`}>
              {requirement.priority} Priority
            </span>
          )}
        </div>
        
        <h1 className="font-display-lg text-display-lg text-on-background font-bold flex items-center gap-2">
          {requirement.title}
          {requirement.aiGenerated && (
            <span className="inline-flex items-center gap-1 bg-[#1E707D]/10 text-[#1E707D] px-2 py-0.5 rounded text-[12px] font-bold shrink-0 mt-1" title="Generated by AI">
              <span className="material-symbols-outlined text-[14px]">auto_awesome</span> AI
            </span>
          )}
        </h1>
        <p className="font-body-md text-body-md text-secondary mt-1 flex items-center gap-2">
          <span className="material-symbols-outlined text-[16px]">person</span>
          Owner: {(() => {
            const activeProject = useProjectStore((state) => state.activeProject);
            const projectMembers = activeProject?.members || [];
            const member = projectMembers.find(m => m.id === requirement.ownerId);
            return member ? (
              <span className="flex items-center gap-1.5">
                <span 
                  className="w-5 h-5 rounded-full text-white flex items-center justify-center font-bold text-[9px] shadow-sm"
                  style={{ backgroundColor: member.bg || '#1E707D' }}
                >
                  {member.initials}
                </span>
                <span className="font-medium text-on-surface">{member.name}</span>
              </span>
            ) : <span className="italic">Chưa phân công</span>;
          })()}
        </p>
      </div>
      
      <div className="flex gap-3 items-center mt-2 md:mt-8">
        {requirement.status === 'IN_REVIEW' && (
          <Button 
            variant="outline"
            onClick={handleApprove}
            className="text-emerald-700"
          >
            <span className="material-symbols-outlined text-[18px]">check_circle</span> Duyệt (Approve)
          </Button>
        )}
        
        <Button 
          variant={btnVariant}
          onClick={() => setIsSmartSyncModalOpen(true)}
          {...extraProps}
        >
          <span className="material-symbols-outlined text-[14px]">auto_awesome</span>
          {btnText}
        </Button>
      </div>

      <AiSmartSyncAllModal 
        requirementId={requirement.id}
        existingUseCases={requirement.useCases}
        isOpen={isSmartSyncModalOpen}
        onClose={() => setIsSmartSyncModalOpen(false)}
        onSuccess={handleAiModalSuccess}
      />
    </div>
  );
};

export default RequirementDetailHeader;
